### ISSUE TITLE
VSCode: Python cells lose execution ability

### ISSUE THREAD

**Issue by smingerson** [quarto-dev/quarto#104]
I've been using Quarto as an opportunity to learn VSCode, and have been running into a problem. When working in a .qmd file with Python cells, I lose the  ability to execute whole cells with CTRL+SHIFT+ENTER or the "run cell" button. I can send individual lines, I can use the console brought up, but not a whole cell at once. Sometimes when this happens, I'll receive a "not in a valid cell" diagnostic message, or something along those lines, but not always. 

Let me know what other information I can provide to isolate the issue.

**Comment by jjallaire** [comment]
I am not able to repro this locally but I'm sure you have indeed ended up in state where this occurs. My best guess is that something in the tokenization of the source file has gotten the run cell command confused. Could you provide the source to the `.qmd` file where this is occurring? Another thing to do is to execute the **Developer: Toggle Developer Tools** command before attempting the Run Cell and see whether any error messages are logged there when you attempt to run.

**Comment by zykezero** [comment]
Adding on that I also have this issue and I have no idea what information will be relevant to solving it.

**Comment by jjallaire** [comment]
The bit I mentioned above about ::Developer: Toggle Developer Tools:: to see if there are error messages occurring. You should also make sure that you can successfully execute the **Jupyter: Create Interactive Window** command and that you can run Python code there.

**Comment by zykezero** [comment]
Hey @jjallaire 

The jupyter interactive window works fine. This is the error when I click Run Cell.
I'm gonna try and work through it now that I actually have an error code to work off of.

> Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > M: Error: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > M
    at s (c:\Users\perinp\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:1777525)
    at Socket.<anonymous> (c:\Users\myname\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:1777622)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by smingerson** [comment]
Unfortunately I made changes after filing this issue, and no longer have the exact text leading to the problem. I believe it was a syntax error within a dictionary. Attempts this morning to reproduce went nowhere. I'll update if I run into the issue again. Thank you for another great product and support experience!

**Comment by garrettgman** [comment]
@jjallaire I'm running into this issue while following along with the [Hello, Quarto VS Code tutorial](https://quarto.org/docs/get-started/hello/vscode) (solution below). I can render the whole document, but the Run Cell button and its keyboard shortcuts do not run the chunk, but bring up the error seen below:

<img width="548" alt="Screen Shot 2023-08-04 at 4 43 56 PM" src="https://github.com/quarto-dev/quarto/assets/85014/a79b56b1-4577-49bc-b0ce-d28aebe52f9d">

<img width="1136" alt="Screen Shot 2023-08-04 at 4 43 49 PM" src="https://github.com/quarto-dev/quarto/assets/85014/6bbc98dc-873a-47ad-a3bf-c1a88a2f01f8">

Installing the Jupyter extension on VS Code resolved the issue and enabled execution of the code chunks.
