### ISSUE TITLE
How to add metadata to new file in visual editor on Vscode?

### ISSUE THREAD

**Issue by veeravignesh1** [quarto-dev/quarto#105]
Hi,
**Quarto VsCode Version: v1.71.0**
I have configured .qmd files to be opened directly into quarto visual editor as mentioned in the [Docs](https://quarto.org/docs/visual-editor/vscode/). Am unable to add metadata with yaml syntax so had to switch to source mode add metadata and come back into visual editor and start writing the content.

Is there a cleaner way to achieve this?
Is it expected for the visual editor to show up the editing options only after adding metadata to the file?

**Comment by jjallaire** [comment]
Excellent question as I just noticed that the YAML Metadata command is absent from the Insert menu (an oversight!). In the meantime, you can insert new blocks of content by typing `/` (or `Cmd+/`):

<img width="642" alt="Screen Shot 2023-03-04 at 7 36 03 AM" src="https://user-images.githubusercontent.com/104391/222901443-69ed8cc0-8c0f-42cf-a1a3-460115310571.png">

Will remedy the Insert menu issue ASAP..
