### ISSUE TITLE
VSCode: incorrect autocomplete

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto#107]
![image](https://user-images.githubusercontent.com/1813121/223611832-364b492f-f919-407b-be60-4a4da40a5c19.png)

It suggests `column-screen-inset-left` twice. One of the options should be `column-screen-inset-right` instead.

**Comment by kdheepak** [comment]
I’ve noticed a couple of other places where the suggestion is incorrect. I’ll submit either more issues or PRs in the next few days.

**Comment by cscheid** [comment]
Thank you!
