### ISSUE TITLE
VS Code Mac - Lack of Markdown support in source mode

### ISSUE THREAD

**Issue by Zuline** [quarto-dev/quarto#109]
I work almost exclusively in the Source Mode in Quarto for VS Code.

I cannot see any way to get normal Markdown editing support. For instance in an un-ordered list, on pressing return the editor should create another unordered list item - it doesn't. In ordered lists pressing return should create another ordered list element - it doesn't. Similarly with sub lists the editor doesn't support list continuation.

Is this a setting I haven't found or is it functionality to be added?

**Comment by jjallaire** [comment]
Thanks for pointing this out. We took the default markdown editing behaviors as a baseline but we most certainly missed these! (an oversight).  We will remedy this soon.

**Comment by jjallaire** [comment]
I apologize, I thought that these behaviors were part of the default VS Code Markdown editing support and we were somehow missing them (surprising but possible). It however looks like standard `.md` markdown editing in VS Code doesn't implement this either. Inheriting this behavior would have been a pretty straightforward path but it looks like it isn't that simple! We will eventually do this but I don't think we can turn it around as fast as I'd hoped to.

**Comment by jjallaire** [comment]
Interestingly, looking at their source code it looks like Markdown All in One now recognizes `quarto` as a markdown file type (so the list editing behavior would in theory work). It also looks like they haven't released this version yet to the marketplace, so perhaps post an issue there to see when the release is anticipated?

Knowing about this, if we implement something natively we'll need to be sure to not conflict or otherwise interact undesirability with the feature implemented there.

**Comment by Zuline** [comment]
I've done some further testing on this. The list continuation functions appear to be provided my Markdown All in One. Even with it enabled in a Quarto workspace these don't work - so back to your suggestion @jjallaire to find out when they will release their version supporting Quarto,

The `shift` drag image behaviour *seems* to be provided by Dendron...who knew! Enabling Dendron in a Quarto workspace provides that capability. So that's a win of sorts...however Dendron does other stuff that's potentially unhelpful for a Quarto workspace.

**Comment by Zuline** [comment]
Yet more exploration:

`shift` drag for image insertion is *not* working correctly. The path to the image is inserted correctly but the correct Markdown tag is not being inserted so there is some interaction between Quarto and VS Code that's preventing this working correctly. This *is* built in VS Code functionality.

Viewing the Markdown All in One Changelog: [Changelog](https://github.com/yzhang-gh/vscode-markdown/blob/master/CHANGELOG.md#350-20221120) Shows that support was planned for `.qmd` as an additional file type in release 3.5.0 but for some reason it never made it - it's struck through in the changelog. Adding `qmd` to the settings.json doesn't work.

**Comment by jjallaire** [comment]
Thanks, we'll take a look at shift-drag image insertion Looking at the all-in-one source code it looks like they do now have the `quarto` file type as a full peer of `markdown` so when they do release all of those features should come online.

**Comment by jjallaire** [comment]
I've implemented shift-drag image insertion here: https://github.com/quarto-dev/quarto/commit/a6ea98a0e149d497d2ccf2eda7fd20174f8ceb92. This will be available in the next release (~ a week or two).

I am going to defer to the release of the updated All in One w/ integrated Quarto support for list editing features.

**Comment by Zuline** [comment]
Thanks for this!

Given the reliance on Markdown All in One, is there a way to make it a "recommended" extension when someone installs Quarto? I believe I've seen other extensions where they pop up a message lower right, recommending that further extensions are also installed and allowing you to choose for that to happen. That would make the reliance neater and prevent head scratching.

> I've implemented shift-drag image insertion here: [a6ea98a](https://github.com/quarto-dev/quarto/commit/a6ea98a0e149d497d2ccf2eda7fd20174f8ceb92). This will be available in the next release (~ a week or two).
> 
> I am going to defer to the release of the updated All in One w/ integrated Quarto support for list editing features.

**Comment by jjallaire** [comment]
I'm not super comfortable with making it recommended with really vetting whether it provides a high quality experience. I've seen a lot of markdown extensions for VS Code that are buggy/flakey/incompletely/annoying. I'm happier with the idea that:

(1) Motivated users discover Markdown All in One and install it; or

(2) The very most important functionality be implemented natively by the Quarto extension (the list editing you brought up probably falls in the this category, I just don't have time right now to ensure that we do it well thus the reliance on All In One.
