### ISSUE TITLE
consider sending python code to radian for mixed language documents

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto#110]

**Comment by jooyoungseo** [comment]
@jjallaire  After the meeting, I realized that this is not necessarily an `raidan` dependent feature. Instead, this is whether we send Python cell to `reticulate::repl_python()`. Even legacy rterm can be used.

Below are my suggestions:

1. In VSCode extension, add user configurable setting to send Python code to `reticulate::repl_python()`.

1. When it's true, send the Python cell to currently open R console (it does not matter whether it's radian or rTerm).

**Comment by jjallaire** [comment]
The problem is that we still don't have a way of knowing whether `reticulate::real_python()` is enabled. Ideally the R extension would open up a new API that lets us tag the language of what is being sent as either R or Python (so that it can activate/deactivate the Python REPL as required)

**Comment by jjallaire** [comment]
Just implemented support for reticulate here: https://github.com/quarto-dev/quarto/commit/5b1e799aae821798d28e24e0dddca0fa31544884

Will be available in the next release (likely later this week)

**Comment by jooyoungseo** [comment]
Awesome! I am so much looking forward to it. I will leave my comment once I verify it.

**Comment by jooyoungseo** [comment]
Apparently, `conda` path does not seem to be properly escafed on Windows. It says:

``` r
> C:/Users/jseo1005/AppData/Local/miniconda3/Scripts/activate
Error: unexpected '/' in "C:/"
Run `rlang::last_trace()` to see where the error occurred.
```


I have tested with the following `test.qmd`, and executed the first cell:

````
    ---
title: test
format: html
---

```{python}
print("hello")
```


```{r}
print("hello")
```
```

````

**Comment by jooyoungseo** [comment]
If I re-execute the first cell again, it starts working.

**Comment by jinlin82** [comment]
I still prefer sending python code to jupyter interactive console for mixed language documents.

It would be nice if there is an option we can choose sending python code to jupyter interactive console or to reticulate.

Thanks.

**Comment by jjallaire** [comment]
Thanks for the feedback! I've added an option for this here: https://github.com/quarto-dev/quarto/commit/bc707df49fd6954d899b130def543fd711d206d5 (this will be available in the next release which should be by end of this month)
