### ISSUE TITLE
Set font family for visual editor?

### ISSUE THREAD

**Issue by githubpsyche** [quarto-dev/quarto#117]
It looks like this line here 

https://github.com/quarto-dev/quarto/blob/6ba518bc0fbfe530f61d439a97f6be14a31d0d3f/apps/vscode-editor/src/theme.ts#L82 

sets the font family for the visual editor. Can this be exposed as a configurable setting of the quarto extension? Or is it already exposed somewhere?

**Comment by jjallaire** [comment]
Just implemented this here: https://github.com/quarto-dev/quarto/commit/5abae1f79b05572f42ed907318f1dd1c90582ac8

It will default to the font used for Markdown Preview (which IMO looks better for this purpose than the default we had chosen, at least on Mac OS).

This will be available in the next release (date TBD but normally within 7-10 days).
