### ISSUE TITLE
Inconsistent behaviour in the crossref index in the RStudio visual editor

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto#120]
Create the following Quarto document with a figure and table crossref and open it in RStudio in the visual editor.

````
---
format: html
---

The table below shows cars.

```{r}
#| label: tbl-cars
#| tbl-cap: "Cars table."

library(knitr)
kable(head(cars))
```

The figure below also shows cars.

```{r}
#| label: fig-cars
#| fig-cap: "Cars figure."

plot(cars)
```
````

Then, follow the steps below to reproduce the problem:

- Render the document once and then attempt to insert a crossref with Insert > Cross Reference and confirm that everything works as expected: both `fig-cars` and `tbl-cars` are available to be cross-referenced. Insert one of these.
- Then, make any change to the document, e.g., remove the crossref that you just inserted, save the document, but don't render it.
- Attempt to insert another crossref with Insert > Cross Reference. Only `fig-cars` is available, not `tbl-cars`. (Based on my testing, this is true regardless of where you make the change and where you try to insert the crossref, including a change in the code as opposed to the prose.)
- Now, render the document with the change and then go to the Insert > Cross Reference menu. Both crossrefs are available again. Don't insert a new crossref, instead close out of the crossref menu.
- Next, add some text after "The figure below also shows cars." Save the document and then click on the line "The table below shows cars." and go to Insert > Cross Reference. Neither of the crossrefs show up.

You can see a screencast of me trying out a bunch of permutations of these actions at https://drive.google.com/file/d/14FcMU6AeU7OkDtBKAEUbjejQEQyLhWUX/view?usp=sharing.

I'm using:

- Quarto 1.3.276
- RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

```
Mines-MacBook-Pro---Posit:~ mine$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.276
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.1
      Path: /usr/local/bin/python3
      Jupyter: 4.9.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

**Comment by ronblum** [comment]
Tested with Quarto version 1.3.299 and RStudio Desktop 2023.03.1+422 on MacOS 13.2. Testing with the above steps work. However, I found one condition in which the cross references don't show up:
1. Create a new Quarto document.
2. In source mode, paste the code above.
3. Switch back to visual mode and click somewhere in the body of the document.
4. <kbd>Insert -> Cross Reference</kbd>
    - Neither of the cross references is available.
5. Save the file.
6. <kbd>Insert -> Cross Reference</kbd>
    - Neither of the cross references is available.
7. Add another character.
8. <kbd>Insert -> Cross Reference</kbd>
    - The cross references now appear.

**Comment by ronblum** [comment]
Step 8 isn't consistent: Sometimes the cross references never appear. Instead, the message "Working" appears, and never goes away. The Insert -> Cross Reference can be closed, but the IDE becomes unusable—files can be edited but not saved, the Console is unresponsive, you can't switch between panes, etc. The only thing that can be done is to quit RStudio and restart.
