### ISSUE TITLE
VSCode Syntax highlighting for citations captures period, incorrectly 

### ISSUE THREAD

**Issue by jeremiahpslewis** [quarto-dev/quarto#121]
See below, the syntax highlighting captures the period after a citation key, incorrectly; this doesn't happen for other punctuation.

<img width="80" alt="Screenshot 2023-03-22 at 18 03 45" src="https://user-images.githubusercontent.com/4462211/226982613-3ac64f52-9ad1-40d6-85c1-7f08eae8a56d.png">
<img width="51" alt="Screenshot 2023-03-22 at 18 03 38" src="https://user-images.githubusercontent.com/4462211/226982621-db1dbad0-059d-45ef-b655-520a0a34720e.png">
<img width="64" alt="Screenshot 2023-03-22 at 18 03 33" src="https://user-images.githubusercontent.com/4462211/226982623-696b4305-5430-41a6-add0-21b1293a6625.png">

**Comment by jjallaire** [comment]
Thanks for reporting this! Fix is here: https://github.com/quarto-dev/quarto/commit/8aa0f3fa342020c64965872fa551467db152f88c
