### ISSUE TITLE
Quarto: Equation doesn't recognize any inline equation after the first

### ISSUE THREAD

**Issue by Mjvolk3** [quarto-dev/quarto#132]
Latex:

matrix $A$ and $B$

Commented Latex for easy display:

`matrix $A$ and $B$`

If I place my cursor at the `|`, `$|A$` I see:

![image](https://user-images.githubusercontent.com/48566106/230087511-857e971d-3098-4c35-9703-3f445a41fe40.png)

If I place my cursor at the `|` , `$|B$`, there is no update in the Quarto: Equation box.

**Comment by ahan98** [comment]
Same issue for me as well. Very annoying

**Comment by jjallaire** [comment]
Thanks for reporting this! It should be fixed here: https://github.com/quarto-dev/quarto/commit/133d3428e206e34f1c2728009e6c75cc8ecbddfa (release w/ this fix should be out in 7-10 days)
