### ISSUE TITLE
quarto assumes all files in a single folder when creating `edit on github` links

### ISSUE THREAD

**Issue by pvgenuchten** [quarto-dev/quarto#134]
Reproduce:
- create a quarto website, add qmd files at multiple levels in a folder hierarchy
- configure [github edit links](https://quarto.org/docs/websites/website-navigation.html#github-links) (repo-url, repo-actions)
- preview website

Notice that edit links point to files as-if-in root folder only, expected: links include path on the hierarchy

Maybe I missed in docs, assuming files in a hierarchy are supported...

**Comment by cderv** [comment]
Our doc uses the edit links e.g. this page https://quarto.org/docs/output-formats/pdf-basics.html and this will sent you correctly to `docs/output-formats/pdf-basics.qmd` in the Github repo. 

The `quarto-web` repo for our doc (https://github.com/quarto-dev/quarto-web) uses hierarchy and it seems to work

Do you have an example website or a configuration to share ?

**Comment by cscheid** [comment]
I think you're looking for `repo-subdir`

**Comment by pvgenuchten** [comment]
Thank you for your answers, indeed you are correct, it works as expected, I made a typo but got confused on how github manages 404's
