### ISSUE TITLE
[Feature Request] Markdown highlight in vscode

### ISSUE THREAD

**Issue by PeterWang-dev** [quarto-dev/quarto#137]
Quarto does not provide a good highlighting of markdown source code compared with Markdown all in one extensions, for example, the list, of which number or label is not lighted up.

Sufficient highlighting really helps a lot when reading markdown source code.

**Comment by jjallaire** [comment]
Hi thanks for reporting this! Our syntax highlighting is entirely derived from the default highlighting so it shouldn't differ much if at all. In this case we actually had an oversight on how we labeled the list and block quote tokens which I remedied here: https://github.com/quarto-dev/quarto/commit/98c86cf8aad0b4747ac9e06dbb7ff2dc5f26799e

This will be available in a release within a week or two.
