### ISSUE TITLE
New version of VS Code breaks Run Cell button for jupyter qmd

### ISSUE THREAD

**Issue by julieinsan** [quarto-dev/quarto#14]
Hi!
I've recently updated VS Code to 1.73.0. Since then, when I click on "Run Cell" on a python code chunk in a qmd file (jupyter: python3 engine), the interactive python kernel (running the correct kernel for the project) opens, but the code does not get transferred to it.  So, I have to manually copy the code from the code chunk into the repl. 

Here are the details of my VS Code installation:
Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

I am using conda environments, the kernel is py 3.10.4 and here's my conda list:

Name                    Version                   Build  Channel
anyio                     3.5.0           py310haa95532_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0          py310h2bbff1b_0
asttokens                 2.0.5              pyhd3eb1b0_0
attrs                     21.4.0             pyhd3eb1b0_0
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.11.1          py310haa95532_0
bleach                    4.1.0              pyhd3eb1b0_0
brotlipy                  0.7.0           py310h2bbff1b_1002
bzip2                     1.0.8                he774522_0
ca-certificates           2022.07.19           haa95532_0
certifi                   2022.9.24       py310haa95532_0
cffi                      1.15.1          py310h2bbff1b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
colorama                  0.4.5           py310haa95532_0
contourpy                 1.0.5                    pypi_0    pypi
cryptography              37.0.1          py310h21b164f_0
cx-oracle                 8.3.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1           py310hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.4             py310haa95532_0
et_xmlfile                1.1.0           py310haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
fonttools                 4.37.4                   pypi_0    pypi
glib                      2.69.1               h5dc1a3c_1
greenlet                  1.1.3                    pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
icu                       58.2                 ha925a31_3
idna                      3.3                pyhd3eb1b0_0
ipykernel                 6.15.2          py310haa95532_0
ipython                   8.4.0           py310haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
jedi                      0.18.1          py310haa95532_1
jinja2                    3.0.3              pyhd3eb1b0_0
jpeg                      9e                   h2bbff1b_0
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.4.0           py310haa95532_0
jupyter                   1.0.0           py310haa95532_8
jupyter_client            7.3.5           py310haa95532_0
jupyter_console           6.4.3              pyhd3eb1b0_0
jupyter_core              4.10.0          py310haa95532_0
jupyter_server            1.18.1          py310haa95532_0
jupyterlab                3.4.4           py310haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.12.0          py310haa95532_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
kiwisolver                1.4.4                    pypi_0    pypi
libclang                  12.0.0          default_h627e005_2
libffi                    3.4.2                hd77b12b_4
libiconv                  1.16                 h2bbff1b_2
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.2                h2bbff1b_0
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
lz4-c                     1.9.3                h2bbff1b_1
markupsafe                2.1.1           py310h2bbff1b_0
matplotlib                3.6.1                    pypi_0    pypi
matplotlib-inline         0.1.6           py310haa95532_0
mistune                   0.8.4           py310h2bbff1b_1000
nbclassic                 0.3.5              pyhd3eb1b0_0
nbclient                  0.5.13          py310haa95532_0
nbconvert                 6.4.4           py310haa95532_0
nbformat                  5.3.0           py310haa95532_0
nest-asyncio              1.5.5           py310haa95532_0
notebook                  6.4.12          py310haa95532_0
numpy                     1.23.3                   pypi_0    pypi
openpyxl                  3.0.10          py310h2bbff1b_0
openssl                   1.1.1q               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.5.0                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pcre                      8.45                 hd77b12b_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.2.0                    pypi_0    pypi
pip                       22.1.2          py310haa95532_0
ply                       3.11            py310haa95532_0
prometheus_client         0.14.1          py310haa95532_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
prompt_toolkit            3.0.20               hd3eb1b0_0
psutil                    5.9.0           py310h2bbff1b_0
pure_eval                 0.2.2              pyhd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9           py310haa95532_0
pyqt                      5.15.7          py310hd77b12b_0
pyqt5-sip                 12.11.0         py310hd77b12b_0
pyrsistent                0.18.0          py310h2bbff1b_0
pysocks                   1.7.1           py310haa95532_0
python                    3.10.4               hbb2ffb3_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2          py310haa95532_0
pytz                      2022.1          py310haa95532_0
pywin32                   302             py310h2bbff1b_2
pywinpty                  2.0.2           py310h5da7b33_0
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.2.0          py310hd77b12b_0
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_4
qtconsole                 5.3.2           py310haa95532_0
qtpy                      2.2.0           py310haa95532_0
qtwebkit                  5.212                h3ad3cdb_4
requests                  2.28.1          py310haa95532_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                63.4.1          py310haa95532_0
sip                       6.6.2           py310hd77b12b_0
siuba                     0.3.0                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.2.0           py310haa95532_1
soupsieve                 2.3.1              pyhd3eb1b0_0
sqlalchemy                1.4.41                   pypi_0    pypi
sqlite                    3.39.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
terminado                 0.13.1          py310haa95532_0
testpath                  0.6.0           py310haa95532_0
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
tornado                   6.2             py310h2bbff1b_0
traitlets                 5.1.1              pyhd3eb1b0_0
typing-extensions         4.3.0           py310haa95532_0
typing_extensions         4.3.0           py310haa95532_0
tzdata                    2022c                h04d1e81_0
urllib3                   1.26.11         py310haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1           py310haa95532_1
websocket-client          0.58.0          py310haa95532_4
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.5.2           py310haa95532_0
win_inet_pton             1.1.0           py310haa95532_0
wincertstore              0.2             py310haa95532_2
winpty                    0.4.3                         4
xz                        5.2.5                h8cc25b3_1
zeromq                    4.3.4                hd77b12b_0
zlib                      1.2.12               h8cc25b3_3
zstd                      1.5.2                h19a0ad4_0

**Comment by danieltomasz** [comment]
@jjallaire does it work for you with 1.74.1?

**Comment by jjallaire** [comment]
Yes, Jupyter Run Cell does indeed work correctly for me in v1.74.1
