### ISSUE TITLE
[Visual Studio Code] Tiny Visual Glitch in Visual Editor with Citation

### ISSUE THREAD

**Issue by joelvonrotz** [quarto-dev/quarto#140]
Hello

I've noticed a tiny visual glitch in the visual editor in VSCode when using citations and cross reference. My perfectionist ass vision can't dismiss it, but it doesn't impact the output of the document and it's not world ending.

Below is how it looks like in VSCode, see the curved brace being blue. When adding a space, it removes the blue color and adds a space between the reference and the brace:

![image](https://user-images.githubusercontent.com/41155337/233114969-97f92bf6-f618-429d-861c-89812c3c5bf0.png)

![image](https://user-images.githubusercontent.com/41155337/233117104-c9f99b32-09f4-4a67-91ad-cedb990b5ae0.png)

This is how it looks in RStudio:

![image](https://user-images.githubusercontent.com/41155337/233114898-578263f4-e2b8-49e8-9d1d-47b9fdc8506e.png)

Would be cool to fix :)

**Comment by jjallaire** [comment]
Thanks for pointing this out! Should be resolved here: https://github.com/quarto-dev/quarto/commit/316f79042ff65c061ed58876b5f50ddc053e112c (release w/ this should be out in a week or two)

**Comment by joelvonrotz** [comment]
Thank you very much!
