### ISSUE TITLE
[Bug] Sidebar preiview conflict with GitLens

### ISSUE THREAD

**Issue by PeterWang-dev** [quarto-dev/quarto#147]
This happed even not in `.qmd` files.

**Comment by jjallaire** [comment]
We need a few more details here than "Sidebar preview conflict with GitLens". I have GitLens installed and quarto preview works as well as the sidebar "Quarto: Equation" preview. If you could provide details/screenshots on the behavior you are seeing and then describe the behavior you expect to see that would be much appreciated.

**Comment by jjallaire** [comment]
I'm still not 100% sure what the actual problem is from your screenshot, but I did make a change to only have the Quarto Assist panel update when within a Quarto document: https://github.com/quarto-dev/quarto/commit/c64fe867121d565c9d54e7172be6a39a62e7714d

**Comment by PeterWang-dev** [comment]
Emm, the issue still exists. To be more accurate, the recurrence step:

1. Open a `.qmd` file and use sidebar to preview an equation;
2. Open another python file, put the cursor in this python file;
3. Then get back to `.qmd` file and put the cursor at any position, you can see the error like this one:
    
    ![image](https://user-images.githubusercontent.com/59994316/235446716-9eded469-4372-41be-b7dd-4340be79f093.png)

Three things are out of expectation:

1. Seems Quarto and GitLens use the same sidebar panel;
2. When getting into the python file (another file but `.qmd` ), the preview sidebar should be disable or and GitLens info panel should replace the preview bar;
3. When get back to `.qmd` file, the last commit info from GitLens is rendered by preview panel.

Moreover, you can see that the panel can only be occupied by either Quarto or GitLens. Is there any means to make a new separate panel for Quarto so that the GitLens and Quarto are not conflict with each other.

@jjallaire

**Comment by jjallaire** [comment]
I have made a change to prevent Quarto from rendering content from GitLens here: https://github.com/quarto-dev/quarto/commit/18dc337244c3087a59c1b1158d6909b89a6d5605

We don't in fact share any context with GitLens (all of that is user  / vscode managed).
