### ISSUE TITLE
Syntax highlight of plantuml code in code blocks

### ISSUE THREAD

**Issue by FabienSe** [quarto-dev/quarto#148]
I was wondering is it is possible to inject grammar provided by the extension <https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml> into code blocks in quarto documents ?

So the following code would be highlighted:

![image](https://user-images.githubusercontent.com/106662952/234533165-0b0b4500-d13d-4e1c-957a-71e6e5c85ebd.png)

I saw some code in `build-lang.js` in syntaxes folder which seems to be related to that.

Thanks for your help !

**Comment by jjallaire** [comment]
Thanks for pointing this out, implemented here: https://github.com/quarto-dev/quarto/commit/5e01103206ce9d64e7831dbb4b7b083ed3dc9b0b (should be available in a release within the next week or two)
