### ISSUE TITLE
R code chunks in VS Code visual mode do not auto-continue

### ISSUE THREAD

**Issue by JosiahParry** [quarto-dev/quarto#149]
Steps to repro:

1. From command pallette create new quarto document
2. save to random location (remember to delete it)
3. Right click editor to activate visual editing (not available without saving for some reason)
4. cmd + shift + i for new code chunk replace `python` with `r`
5. Add the following lines to your code chunk:  `library(base)` and `library(stats)`
6. press command enter to execute and repeat. 

Note that the cursor in the code block continues but the line executed remains the first one. 

<img width="382" alt="image" src="https://user-images.githubusercontent.com/13534508/234604407-136a1a2f-efac-4630-9b45-6821b2e77284.png">

**Comment by jjallaire** [comment]
Thanks for reporting and for the easy repro! Should be fixed here: https://github.com/quarto-dev/quarto/commit/789f4c953e5ca6b317a85ccbf1a19cd5ff9d8d8b
