### ISSUE TITLE
R code chunks in VS Code code visual editor to not recognize highlight all

### ISSUE THREAD

**Issue by JosiahParry** [quarto-dev/quarto#152]
1. From command pallette create new quarto document
2. save to random location (remember to delete it)
3. Right click editor to activate visual editing (not available without saving for some reason)
4. cmd + shift + i for new code chunk replace python with r
5. Type `library(stats)` 
6. try to highlight everything with `cmd + a` note that nothing is highlighted.

Quarto version 1.3.313

**Comment by jjallaire** [comment]
Thanks for reporting! Should be resolved here: https://github.com/quarto-dev/quarto/commit/c426363c40f07d245ae7f1344236ce4d7bc66d07
