### ISSUE TITLE
Support `engine` metadata in YAML autocompletion

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto#155]
In VSCode quarto extension, `engine` metadata is not provided in the YAML autocompletion.

**Comment by jjallaire** [comment]
Thanks for pointing this out. We had it marked `hidden` for some reason. I've remedied this here: https://github.com/quarto-dev/quarto-cli/commit/bdd498bcbcedeb7641e351f00005ac91738dacd7 (you'll see this change when running the v1.4 pre-release as of tomorrow's build)
