### ISSUE TITLE
VSCode: toggling **comment** doesn't work work for mermaid cell

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto#157]
1. Create a mermaid cell in qmd file.

1. `Toggle Line Comment, Control+/`

1. `%%` is not inserted.

**Comment by jjallaire** [comment]
Thanks for reporting this! Resolved here: https://github.com/quarto-dev/quarto/commit/675b59b9e412c75e8650cb7feb2e2b48239de523
