### ISSUE TITLE
quarto cannot activate and render until  the python env is set in vscode

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto#158]
I created a new profile in Vsode (the previous profile had a working quarto plugin instance)
I installed the quarto extension, I tried to render both qmd and ipynb quarto files, but I only saw info "Quarto: activating ..." and nothing happened.

Only after I installed Python environment manager and set the the env to the same as was defined in the notebook I was able to render them.

Until then I wasn't able to render anything and I didnt received any error message.
I would expect that even if there something not set in the environment, the user  receive the meaningful information that allow him to find the cause of this problem.

I am using quarto 1.3.340, VSCode 1.77.3 and the plugin version v1.83.0

**Comment by jjallaire** [comment]
It's possible that there is an error message sitting in the Developer Tools Console. If you do **Developer: Toggle Developer Tools** before trying to activate do you see any messages there?

**Comment by danieltomasz** [comment]
Cannot reproduce when setting up new profile again, so I am closing this issue
