### ISSUE TITLE
`jupyterlab-quarto` does not render markdown cells starting with a horizontal rule

### ISSUE THREAD

**Issue by seeM** [quarto-dev/quarto#162]
For example, these cells are rendered as empty:

```markdown
---
```

```markdown
---

Start of a new paragraph.
```

I assume it has to do with parsing frontmatter.

**Comment by seeM** [comment]
cc @dragonstyle (please let me know if there's a better way to report these!)

**Comment by dragonstyle** [comment]
Thanks for reporting this - this should be fixed in the `0.1.45` release of the extension, which is available now!

Reporting here is perfect - I review all the bugs so this is great!
