### ISSUE TITLE
Visual studio Quarto assist panel no longer works outside of .qmd files

### ISSUE THREAD

**Issue by ihough** [quarto-dev/quarto#164]
As of v1.83.0 of the Quarto extension for Visual Studio, the assist panel only shows function help/documentation when editing a *.qmd file.

In v1.82.0 and earlier the assist panel showed help/documentation for other file types (e.g. *.R, *.ipynb, *.py).

Possibly caused by https://github.com/quarto-dev/quarto/commit/c64fe867121d565c9d54e7172be6a39a62e7714d?

Would it be possible to restore the previous functionality, or at least have a preferences setting to enable the assist panel in all file types?

**Comment by jjallaire** [comment]
Yeah we did that to address some conflicts w/ GitLens however in the meantime we put in another GitLens mitigation that should equally handle the conflicts. I'll restore the old behavior for other file types.

**Comment by jjallaire** [comment]
Done here: https://github.com/quarto-dev/quarto/commit/ee27f28487642b7082f003366449351853358cbd
