### ISSUE TITLE
Is this possible? An extension to replace Pandoc-flavored Markdown with my favorite markdown format

### ISSUE THREAD

**Issue by raj-magesh** [quarto-dev/quarto#169]
Would it be possible to use Quarto with input text files that aren't written in Pandoc-flavored markdown if the format can be converted to the Pandoc AST using a different reader?

**Comment by jjallaire** [comment]
You would need to chain together two commands -- one to convert to pandoc markdown and one to call quarto. Note that you can call pandoc directly using `quarto pandoc` so something like this to read from another format to markdown

```terminal
quarto pandoc -s foo.rst -o foo.md
quarto render foo.md
```
