### ISSUE TITLE
 'quarto.newNotebook' not found in VSC Insiders

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto#174]
When trying to create new ipynb via Cmd + shift + P in VSCode Insiders I recived this error
```
Command 'Quarto: New Notebook (ipynb)' resulted in an error command
 'quarto.newNotebook' not found in VSC Insiders
```
Vscode 1.78.2  Work without problem

Version: 1.79.0-insider
Commit: 2d416df5f00253f5ebd60d2f08508a440747fd8d
Quarto v1.85.0

I am on Mac 13.4

**Comment by jjallaire** [comment]
I'm not able to repro this (on the insiders version I just downloaded).If you open up the developer console (**Developer: Toggle Developer Tools**) do you see any errors logged when you execute this command?

**Comment by danieltomasz** [comment]
The problem is not about notebook creation, but activating quarto ( I switched from stable code today and I didnt noticed)
```
Activating extension 'quarto.quarto' failed: Unable to parse decrypted password.
```

It also happening in a fresh profile (Python defualt extension + Jupyter  + quarto )

**Comment by jjallaire** [comment]
From Googling it looks like may be somehow related to VS Code Settings Sync? Are you using that?

Also, if you could execute the **Developer: Toggle Developer Tools** you should see a stack trace that points to the exact line of code that is throwing.

**Comment by danieltomasz** [comment]
Hi @jjallaire thanks for comment, after latest Vscode update I switched back to stable, and I dont have the problem there so I will close this issue
