### ISSUE TITLE
Pasting from Source Editor to Visual Editor escapes Markdown

### ISSUE THREAD

**Issue by jgsw** [quarto-dev/quarto#185]
If you paste plain text Markdown (e.g. from another file open in the source editor) into the visual editor, then all the Markdown constructs are backslash escaped. A user might sometimes want this to happen, but it's probably more likely that they would like the plain text pasted to be interpreted _as Markdown_ within the visual editor. 

The current implementation also leads to confusing results in practice. For example, if you paste text that is marked up as bold (surrounded by two asterisks on either side) from the source editor into the visual editor, what appears in the visual editor is text that is both bold and also surrounded by backslash escaped asterisks, i.e. **\*\*bold text\*\***.  

My suggestion would be either not to backslash escape plain text pasted into the visual editor at all, or failing that, add a "Paste as Plain Text" option which would allow pasting without backslash escapes.

**Comment by jjallaire** [comment]
Thanks for the feedback! We've implement rendering of markdown on paste here: https://github.com/quarto-dev/quarto/commit/83e1bb26a9b1e1760c26dddbaa27fc62f21391cd. Note there is also support for Cmd+Shift+V to paste as plain text w/o formatting. This will be available in the next release (likely in the next couple of weeks)
