### ISSUE TITLE
[Feature Request] Rendering Quarto Markdown (qmd) in multiple formats simultaneously using Quarto extension for VScode by pressing Ctrl + Shift + K

### ISSUE THREAD

**Issue by CLRafaelR** [quarto-dev/quarto#186]
This post is originally published in [StackOverflow](https://stackoverflow.com/q/76278216/10215301); however, none of response has been received for 10 days, I repost it here as a feature request.

I am rendering a qmd file using the [Quarto extension](https://quarto.org/docs/tools/vscode.html) in VScode. As mentioned in the [official documentation](https://quarto.org/docs/tools/vscode.html#render-and-preview), you can press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>K</kbd> to perform the rendering. However, simply pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>K</kbd> will only render the format specified at the top level of `format` key in the YAML of the qmd file. For instance, you will produce only `.docx` file out of the following `mwe.qmd`, and you have to comment out `docx: default` to produce a PDF.

Of course, executing the command `quarto render mwe.qmd` in the command line will render all the formats specified under the `format` key in the YAML of `mwe.qmd` at once. Nevertheless, I would like to render in all the formats specified in the YAML by just pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>K</kbd> (or <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>K</kbd>). Is it possible to achieve this by modifying the keybindings in VScode or changing the settings of the Quarto extension? If anyone is familiar with the configuration methods, please let me know.

# mwe.qmd

```yaml
---
format:
  docx: default
  pdf: default
---
    
Hello, world. Please render me to a docx and pdf simultaneously!
```

**Comment by jjallaire** [comment]
I implement this behavior here: https://github.com/quarto-dev/quarto/commit/d54b78316564d31c0dafcf13fe19a082bd123ad2 (this is not yet released but should be within a couple of weeks)

Note that this currently requires the pre-release of Quarto v1.4 (v1.4.104 or higher) since a small change in quarto-cli was required to get this to work properly. We will try to back port that fix to v1.3 soon.
