### ISSUE TITLE
Quarto VS Code on Ubuntu 18.04: ModuleNotFoundError: No module named 'nbclient'

### ISSUE THREAD

**Issue by wuffi** [quarto-dev/quarto#187]
I would like to write documents, which directly include the evaluation results of the *Sage* computer algebra system.
Thanks to the excellent work of the *Sage* and *Quarto* developers, I can already connect to the *Sage* *Jupyter* kernel and evaluate *Sage* expressions within a `Untitled-1.qmd` file, but rendering the document to PDF yields the following error:
```
quarto preview /home/user/Desktop/Untitled-1.qmd --to pdf --no-browser --no-watch-inputs
user@thinkpad:~/Desktop$ quarto preview /home/user/Desktop/Untitled-1.qmd --to pdf --no-browser --no-watch-inputs

Starting sagemath kernel...Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
```
This is unexpected, because the *Python* kernel works (and *Sage* is actually mainly based on *Python*). In addition, running and exporting a *Sage* `*.ipynb` notebook to PDF works.

My `/usr/share/jupyter/kernels/sagemath/kernel.json` looks like this:
```
{"display_name": "SageMath 8.1", "argv": ["/usr/bin/sage", "--python", "-m", "sage.repl.ipython_kernel", "-f", "{connection_file}"], "display_name": "sagemath", "language": "sagemath"}
```

I'm running *VS Code* 1.78.2 on *Ubuntu 18.04* with *SageMath* 8.1 with *Quarto* 1.3.361.

**Comment by jjallaire** [comment]
We depend on a few Python packages for communicating with the Jupyter kernel. The specific packages are `jupyter_core`, `nbformat`, `nbclient`, and `ipykernel` (they can all be installed w/ `pip install jupyter`). If you run `quarto capabilities` from the shell you'll which versions (if any) of these packages we are detecting.

**Comment by wuffi** [comment]
Thanks a lot, this is very helpful and helped me to fix my problem.
