### ISSUE TITLE
[VSCode] List mode in Visual Editor not working as expected

### ISSUE THREAD

**Issue by joelvonrotz** [quarto-dev/quarto#191]
Hello Quarto Team

I've noticed, that in the visual editor in Visual Studio Code the list creation doesn't seem to be working as I expected. I'm using the latest quarto plugin version (v1.86.2).

What I expect when creating a list:

1. Start list with the '-' Symbol (works fine!)
2. Write content and hit Enter for a new List element (this does seem to create a new list element, but seems to be a completely new list)
3. Hit Enter twice to end list mode (this works again)

Following you can see a small gif:

![vscode_list_visual_editor](https://github.com/quarto-dev/quarto/assets/41155337/fcdb9643-2861-428f-87d2-46d3ac4b0071)

**Comment by jjallaire** [comment]
Those are indeed the same list, but reflect the difference between "tight" lists and normal lists. You'll notice there is ellipses at the top right of the list. If you click this (or press F4 while in the list) you can control whether the list is "tight" or not. Further, you can set a global or workspace level default for whether you want tight lists ('spaced' lists are the default):

<img width="667" alt="Screen Shot 2023-05-31 at 7 45 56 AM" src="https://github.com/quarto-dev/quarto/assets/104391/07904a3e-2c56-48fc-86c1-ac70cb333eb0">

**Comment by joelvonrotz** [comment]
Oh oops, my bad, that's exactly what I needed. Didn't know there was a setting for it.
Thank you for your reply!
