### ISSUE TITLE
Quarto VSCode extension v1.3.361 does not recognize executable Julia cells

### ISSUE THREAD

**Issue by dmbates** [quarto-dev/quarto#193]
When working in a document with Julia code cells, I saw that version 1.3.361 of the VSCode extension had become available and upgraded to it.  Immediately I lost the controls to run a cell or run the next cell and, if I move the cursor into a cell and try to execute the cell with <CMD>-<SHIFT>-<RETURN> I get an error "Editor selection is not within an executable cell".

The render button in VSCode still works and `quarto check` in the shell shows the expected version of Quarto (1.3.361) and Julia (1.9.0).  I tried quitting VSCode then restarting in case there were stale configuration settings but no joy.

**Comment by jjallaire** [comment]
I see this too and believe I know the cause. Hopefully a fix forthcoming very shortly!

**Comment by dmbates** [comment]
Thanks, JJ.  I am always amazed at and grateful for the responsiveness of you and others on your Posit team.

**Comment by jjallaire** [comment]
v1.87.1 has just been published and will resolve this error....thanks for reporting, that was a bad one!
