### ISSUE TITLE
VSCode syntax highlighting in OJS chunks

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto#198]
Hi folks,

I notice frequently when writing OJS chunks—especially ones with longer, braced blocks of code—that certain kinds of expression seem to break syntax highlighting.

Here's a pretty small example: I have the same chunk of code open in two contexts:

1. First, with plain JavaScript language selected. I've wrapped it in a function declaration here, but it behaves the same way (as expected) globally.
2. Second, in an OJS chunk with Quarto language selected. Note that highlighting changes when I comment the middle line in and out.

https://github.com/quarto-dev/quarto/assets/6520659/22e7209e-313a-4182-ba6c-aa19948804da

https://github.com/quarto-dev/quarto/assets/6520659/6abfc973-c771-4678-a397-7b3ca7b95a92

I tend to find the line that causes subsequent highlighting to break is either:

* An expression that doesn't feature any assignment (eg. `runSomeFunction()` as opposed to `const x = someFunctionResult()`); or
* An expression that features assignment, but I've broken the line immediately after the assignment operator (`=`)

Explicit semi-colon insertion doesn't seem to affect the behaviour. I'm not sure if this is a Quarto issue, an upstream highlighting issue (ie. whether the Quarto extension defers the OJS chunk highlighting to the JavaScript highlighter or has its own)—or maybe I'm writing bad code here! Cascading syntax highlighting failures often indicate syntactical issues in one's code, but I'm not sure what it is in this case, or if OJS has a different convention here to regular JavaScript.

macOS 13.4
VSCode 1.78.2
Quarto extension 1.87.2
Quarto 99.9.9 (commit d62f23fce)

**Comment by cscheid** [comment]
This is a hard one to fix. We're using a best-effort highlighter (IIRC we pretend it's Java). But because OJS is actually not javascript, it gets confused.

**Comment by jimjam-slam** [comment]
I spoke too soon re. semi-colons. Here's another example that demonstrates both semi-colon and linebreak location:

https://github.com/quarto-dev/quarto/assets/6520659/0b434aaf-d9ac-4aa8-8cd0-87c74b7ba4e1

> This is a hard one to fix. We're using a best-effort highlighter (IIRC we pretend it's Java). But because OJS is actually not javascript, it gets confused.

Makes sense! Happy to just leave it for reference 😊

**Comment by jjallaire** [comment]
We actually treat it as JavaScript: https://github.com/quarto-dev/quarto/blob/main/apps/vscode/syntaxes/build-lang.js#L230-L243

But as @cscheid said this isn't our highlighter its a delegation, so we can't effectively address this issue.
