### ISSUE TITLE
Quick Suggestions appearing in SQL and Python cells regardless of settings

### ISSUE THREAD

**Issue by timothyrenner** [quarto-dev/quarto#2]
Extension version: 1.57.0
VSCode Version:  1.74.1
MacOS Version: 13.0.1 (M1 chip)

I have quick suggestions turned off for everything - trimmed down settings.json file (these entries are identical for user and workspace) here:

```json
{
"editor.quickSuggestions": {
    "comments": false,
    "strings": false,
    "other": false
  },
"[quarto]": {
    "editor.quickSuggestions": {
      "other": false,
      "comments": false,
      "strings": false
    },
 "[sql]": {
    "editor.quickSuggestions": {
      "comments": false,
      "strings": false,
      "other": false
    }
  },
"[python]": {
    "editor.quickSuggestions": {
      "other": false,
      "strings": false,
      "comments": false
    }
  },
  "[r]": {
    "editor.quickSuggestions": {
      "other": false,
      "comments": false,
      "strings": false
    }
}
```

But I still see quick suggestions in Python cells and SQL cells. This doesn't happen with normal markdown documents, Python files, or SQL files. It doesn't happen in the Quarto main document or the R cells, just Python and SQL.

Let me know if there's additional info I can provide.

**Comment by jjallaire** [comment]
Looking at the JSON schema auto-complete for these options, it looks like you need to use `"off"` rather than `false`:

<img width="662" alt="Screen Shot 2022-12-15 at 8 32 05 PM" src="https://user-images.githubusercontent.com/104391/208001455-ede61a5a-6cc3-495c-9ff7-88082675094b.png">

Note that the Quarto extension turns off word based suggestions for some languages (as the markdown words overwhelm the language intelligence) but only sets `quickSuggestions` for `quarto` and YAML (which in any case should be overridable in your own config).

**Comment by timothyrenner** [comment]
I tried both `false` and `"off"` and got the same result - for SQL and Python I see them (also YAML which I had not tried before), but for R and Markdown I do not.

**Comment by jjallaire** [comment]
By adding the following to my user settings file I am able to disable quick suggestions for all languages in qmd:

```json
"[quarto]": {
  "editor.quickSuggestions": {
     "other": "off",
     "comments": "off",
     "strings": "off"
  }
}
```

You can edit this is the settings UI w/ the following query: `@id:editor.quickSuggestions @lang:quarto quick Sug`

Note that suggestions still pop up automatically on trigger characters (e.g. the `.` in Python). You can set `editor.suggestOnTriggerCharacters` to `false` to prevent this. For example:

```json
"[quarto]": {
  "editor.quickSuggestions": {
     "other": "off",
     "comments": "off",
     "strings": "off"
  },
  "editor.suggestOnTriggerCharacters": false
}
```

**Comment by jjallaire** [comment]
No problem, glad that is squared away!
