### ISSUE TITLE
Format code cell based on lang id

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto#21]
Possibly related to quarto-dev/quarto#22. Currently, format code (Alt+Shift+F) does not work. Is it possible for Quarto to flexibly use different formatters depending on the code cell lang id (e.g., r; python) where the formatting code is executed?

**Comment by jjallaire** [comment]
This is now implemented in v1.66.0. Format Document and Format Selection/Cell are both available, keyed off of the cell where the cursor is located (or failing that using the language most frequently appearing within executable cells in the document).

This currently works for Python and Julia. It is enabled for R but there are some things we need to work through w/ the VS Code R extension to make it work properly.

**Comment by harrylojames** [comment]
Thank you for your work on this. Is it possible to get to this to work with OJS (Observable JavaScript) cells?

**Comment by jjallaire** [comment]
The Format Cell command should work in some cases for OJS, however formatters can also end up choking on the special OJS syntax (e.g. view) so it won't always work as expected.
