### ISSUE TITLE
VSCode: Code linting not working with crossref attributes

### ISSUE THREAD

**Issue by PeterWang-dev** [quarto-dev/quarto#210]
When using crossref attributes, code linting is not working.

![图片](https://github.com/quarto-dev/quarto/assets/59994316/3f3b3a37-8ecb-49b9-8e58-aa4c847630a1)

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/quarto-dev/quarto/commit/9d90be5966c465608a99d629be60be7f9a28eebe (will be in the next release within a week or two)
