### ISSUE TITLE
Editor Wrap setting not respected in VSCode

### ISSUE THREAD

**Issue by jordantgh** [quarto-dev/quarto#218]
I have tried 
```
---
editor:
  markdown:
    wrap: 80
---
```

and changing Quarto > Visual Editor: Markdown Wrap Column to 80 in VSC settings. None of that works. It wraps to the width of the editor window, which makes editing on my 1440p screen a bit of a joke. I couldn't find any other people with this issue.

My VSCode 'About' is below, but I am working in WSL (Ubuntu 22.04 LTS, Quarto 1.3.361).

Version: 1.79.2 (system setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by jjallaire** [comment]
That setting controls how markdown is _written_ from the visual editor (i.e. newlines are inserted at 80 characters). It doesn't affect the editing UI (visual or source) at all. 

For the Visual Editor, you can set the maximum editing width using the `quarto.visualEditor.maxContentWidth` setting:

<img width="850" alt="Screen Shot 2023-07-07 at 7 33 12 AM" src="https://github.com/quarto-dev/quarto/assets/104391/46c1a07d-a03c-4adf-8496-edb90616e6c1">

For the source editor, you need to override the default for `.qmd` files as follows (note the `@lang:quarto wrap` query in the settings filter at the top).

<img width="789" alt="Screen Shot 2023-07-07 at 7 38 10 AM" src="https://github.com/quarto-dev/quarto/assets/104391/2b2594d0-1ab1-4a31-90f1-393b3c1330c0">

**Comment by jordantgh** [comment]
Thanks, that clears it up. You might consider re-naming the yaml property to `visual-editor`, I guess you could see where the ambiguity might come in!
