### ISSUE TITLE
Auto-formatting of quarto file

### ISSUE THREAD

**Issue by FabienSe** [quarto-dev/quarto#22]
Hello !

Quarto files are a type of markdown file but still are not detected as a markdown file by Vscode.
Thus it is impossible to use classic formatter to format quarto file.
The more annoying thing is to manually format table.

It is possible to add it to this extension ? Or make it possible to use quarto file with other extension which format markdown file ?

I tired to manually change the association of the file extension(`.qmd`) to markdown in the vscode settings but I am losing all the benefices of this extension.

Thanks a lot for your help

**Comment by boxydog** [comment]
I still have this issue.

Can you point to a tool that auto-formats the markdown in a Quarto file?

It seems unfortunate to close this issue if there's not even one.

**Comment by boxydog** [comment]
Just to point out my real desire: a [pre-commit](https://pre-commit.com/) filter that auto-formats, so our team can agree on a format and stick to it. I might open an issue on this instead of commenting on a closed one.
