### ISSUE TITLE
VSCode browser preview updates to wrong URL after reload

### ISSUE THREAD

**Issue by m-guggenmos** [quarto-dev/quarto#225]
Transferring from https://github.com/quarto-dev/quarto-cli/discussions/6330

Steps to reproduce:

`_quarto.yml`
```
project:
  output-dir: _slides
  render:
    - test.qmd

title: "Title"
author: "John Doe"

format: revealjs
```

`test.qmd`
```
## Heading

Text

## Heading2

Text

## Heading3

Text

## Heading4

Text
```

Quarto settings:
Quarto > Render: Preview Type: internal

1. Start preview, e.g. by clicking "Render" in VSCode on the `test.qmd` file. 
2. Navigate to Heading4 (-> the URL correctly updates to `test.html#/heading4`)
3. Make a change to the text in `test.qmd` under `## Heading4`. Save file.
4. If "Render on save" is enabled, the website preview refreshes automatically. The browser either jumps back to the title page (the URL also changes to the title page's URL/anchor) or to the previous slide and I can't live monitor the changes I have made to the current slide with Heading4. The same issue occurs without "Render on save" when manually clicking the preview browser's reload button.

With a bit further testing after the discussion, I realized that there seems to be a mechanism behind the scenes which monitors in which slide a change has been made and the browser jumps to this place. However, with the above example, this mechanism seems to get it wrong "by one slide" and that's why it often jumps to the previous slide. Even this behavior is not super consistent for me though. Sometimes this mechanism doesn't work at all and it just reloads the present slide irrespective of where the change has been made. Sometimes it jumps back to the first slide. In my limited testing time I couldn't pinpoint this exactly.

VSCode version 1.80.1
Quarto Extension v1.90.0
OS: Ubuntu Linux

**Comment by jjallaire** [comment]
Thanks for reporting this! The issue was that when the `title` is in the `_quarto.yml` file we don't correctly account for the title slides. Fix is here: https://github.com/quarto-dev/quarto/commit/05cb9acde2b2bf5785555964a7cc0814fe181161

Until this is released you should be able to work around this by moving the `title` directly into the `test.qmd` file.

**Comment by m-guggenmos** [comment]
Thanks, that was fast! Will test it when it is available in a new release.

**Comment by m-guggenmos** [comment]
@jjallaire I found a possibly related bug:

_quarto.yml
```
project:
  output-dir: _slides
  render:
    - test.qmd

title: "Title"
author: "John Doe"

format: revealjs
```

test.qmd
```
## First slide heading

    ```{python}
    ```
```

The title on the title slide is "First slide heading". This happens only when including a code block as in this case the python code block.
