### ISSUE TITLE
[Keyboard Accessibility] Provide default keybindings for some useful commands

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto#230]
Type: <b>Feature Request</b>

Please consider adding the following keybindings to Quarto extension by default for keyboard users. Especially, going between code cells seems essential. I am teaching Quarto for keyboard only users and I feel like including the following keybindings would be beneficial instead of letting them manually set their custom bindings. Of Of course, Mac needs to use CMD key instead of Ctrl.

``` json
[
  // Quarto custom keybindings
  {
    "key": "ctrl+pagedown",
    "command": "quarto.goToNextCell",
    "when": "editorTextFocus && editorLangId == 'quarto'"
  },
  {
    "key": "ctrl+pageup",
    "command": "quarto.goToPreviousCell",
    "when": "editorTextFocus && editorLangId == 'quarto'"
  },
  {
    "key": "ctrl+f1",
    "command": "quarto-assist.focus",
    "when": "editorTextFocus && editorLangId == quarto"
  }
]
```

Extension version: 1.91.0
VS Code version: Code - Insiders 1.82.0-insider (83fc3ad9bd553869e8fea3d370d1d2bd438f9e54, 2023-08-04T05:35:09.023Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by jjallaire** [comment]
Thx for the idea! Done here: https://github.com/quarto-dev/quarto/commit/1d873d2ac7b8810e006810cf2d2557e80aefe1f2
