### ISSUE TITLE
Feature Request: Outline/Table of Contents (TOC) to the side in Visual Editor

### ISSUE THREAD

**Issue by digg33** [quarto-dev/quarto#234]
Hello Team,

Thank you for maintaining this extension. In RStudio, the Visual Editor provides an outline button to the right of the toolbar that lists all the headings used in the document as a table of contents. This is very useful for navigating longer documents. Please consider implementing the same for this extension as well.

Thanks,
digg33

**Comment by jjallaire** [comment]
We also have this in the VS Code extension (it's the icon in the top left of the visual editor)

**Comment by digg33** [comment]
> We also have this in the VS Code extension (it's the icon in the top left of the visual editor)

I see it now, thank you! I am using a theme with a black background which hid it very well. I will close this issue now.

![pic1](https://github.com/quarto-dev/quarto/assets/58906128/820c56fb-ae61-41c1-9e31-850e2193a2b2)
![pic2](https://github.com/quarto-dev/quarto/assets/58906128/c54483cb-acb3-4685-b1ef-0334d123ac7d)

**Comment by jjallaire** [comment]
Which theme is that you are using? (I'd like to tweak the colors so they are more visible)
