### ISSUE TITLE
Feature Request: Option to open .qmd files in Visual Mode by default

### ISSUE THREAD

**Issue by digg33** [quarto-dev/quarto#235]
Hello Team,

Thank you for maintaining this extension. Currently the extension always opens any `.qmd` files in source editing mode. As a user of the Visual Editor, it would be very convenient to have an option that causes Visual Mode to be used by default when a new file is opened.

Thanks,
digg33

**Comment by jjallaire** [comment]
If you right click on the editor tab for a qmd you will see an option to use visual mode by default:

<img width="1014" alt="Screen Shot 2023-08-07 at 1 50 58 PM" src="https://github.com/quarto-dev/quarto/assets/104391/75fa8dba-47f3-477a-9439-1d3fcdfb3815">

**Comment by digg33** [comment]
Thank you for your reply - that worked great! For future reference, in my case I had to right-click on the tab, then select "Reopen Editor With..." to invoke the dialog in your screenshot.
