### ISSUE TITLE
VSCode crossref completion not working with latest quarto pre-release.

### ISSUE THREAD

**Issue by PeterWang-dev** [quarto-dev/quarto#237]
**Quarto LSP Output:**

```bash
[Error - 18:56:51] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: spawnSync /opt/quarto/bin/tools/pandoc ENOENT
  Code: -32603
```

**System Information:**

```bash
uname -a
Linux ArchLinux 6.4.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 08 Aug 2023 22:13:48 +0000 x86_64 GNU/Linux
```

**Quarto Check:**

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.309
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Re-produce:**

It happened in every documents after typing in `@` .

**Comment by dragonstyle** [comment]
Sorry for the issue, it is likely a side effect of recent multi-architecture work we've been doing...

Did you use the `deb` file to install Quarto? We're expecting an architecture specific symlink to be present at (the installer should take care of this):

`/opt/quarto/bin/tools/pandoc`

which points to:

`/opt/quarto/bin/tools/${machine_architecture}/pandoc`

Can you check whether you have this symlink and if its resolves correctly?

**Comment by PeterWang-dev** [comment]
> Sorry for the issue, it is likely a side effect of recent multi-architecture work we've been doing...
> 
> Did you use the `deb` file to install Quarto? We're expecting an architecture specific symlink to be present at (the installer should take care of this):
> 
> `/opt/quarto/bin/tools/pandoc`
> 
> which points to:
> 
> `/opt/quarto/bin/tools/${machine_architecture}/pandoc`
> 
> Can you check whether you have this symlink and if its resolves correctly?

Thanks for your quick reply. I checked `/opt/quarto/bin/tools/pandoc`  and found there is even no syslink there.
After creating soft link points to `.../x86_64/pandoc` , it works.

I wonder if this is a Arch Linux specific bug due to improper packaging. After all making a link manually seems just a workaround which should be done by package manager.

**Comment by dragonstyle** [comment]
I think it likely is related to Arch specific packaging. I just opened a PR that I think will remedy the issue going forward. TY for letting us know!

**Comment by PeterWang-dev** [comment]
> I think it likely is related to Arch specific packaging. I just opened a PR that I think will remedy the issue going forward. TY for letting us know!

Appreciate for your concern. However [binary package](https://aur.archlinux.org/packages/quarto-cli-bin-pre-release) still have incorrect syslink. I have made a comment and flagged it under AUR page.

**Comment by PeterWang-dev** [comment]
Closed as completed.
