### ISSUE TITLE
VS Code: Visual mode destroys raw blocks

### ISSUE THREAD

**Issue by kernie** [quarto-dev/quarto#238]
Hi,

I have blocks like: 
```
`\SI{E+13}{\becquerel}`{=latex} `1 E+13 Bq`{=html} `1 E+13 Bq`{=docx}
```
in my book project. 

When I switch to the visual editor and back to source mode the line above ends up in
```
`\SI{E+13}{\becquerel}`{=latex} 1 E+13 Bq `1 E+13 Bq`{=docx}
```
This generates two times the "1E+13" item in Latex or Docx.

Quarto:  1.3.340
Quarto VS Code extension: v1.92.0

**Comment by jjallaire** [comment]
Thanks for reporting this! We have a fix here: https://github.com/quarto-dev/quarto/commit/3c2ca8c537eff515029858b43637e1ef6f44c6f7

Should be released in the next week or so.
