### ISSUE TITLE
vscode plugin preview of markdown files with space in name broken

### ISSUE THREAD

**Issue by drdozer** [quarto-dev/quarto#240]
I have markdown files with spaces in their names. The render preview correctly generates the preview and hosts it. I can access it from a web browser by typing in the corresponding URL. However, within vscode, the preview pane is trunchating the URL at the first space in the name. In the terminal, it has "Browse at" which correctly displays the full URL, but if I hover over it, it's only highlighting up to the first space as the actual URL, and that's the part of the URL that it tries to navigate to.

**Comment by drdozer** [comment]
![image](https://github.com/quarto-dev/quarto/assets/583516/4ebb232a-d42a-430c-b42c-0754dac5f945)

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/quarto-dev/quarto/commit/421e4f9310f37d8eae2fae32937381cd1fc3486e
