### ISSUE TITLE
Format code in the code chunk in the VS code

### ISSUE THREAD

**Issue by guoruizhong** [quarto-dev/quarto#25]
Don't have the function of  formatting code in the code chunk when using quarto in vscode

**Comment by jjallaire** [comment]
This is now implemented in v1.66.0. Format Document and Format Selection/Cell are both available, keyed off of the cell where the cursor is located (or failing that using the language most frequently appearing within executable cells in the document).

This currently works for Python and Julia. It is enabled for R but there are some things we need to work through w/ the VS Code R extension to make it work properly.
