### ISSUE TITLE
VS Code: Poor contrast when selecting text in Visual Editor

### ISSUE THREAD

**Issue by digg33** [quarto-dev/quarto#250]
Hello Team,

Thank you for your work on this project. I have recently started to use the VS Code extension where I noticed that for the "Dark High Contrast" and "Light High Contrast" themes (shipped by default with VS Code), text selections in the visual editor are difficult to see. Please refer to the images below for an illustration.

| Visual Editor | Source Editor |
|--------|--------|
| <img src="https://github.com/quarto-dev/quarto/assets/58906128/b9971262-7f0b-4494-898c-f409daec9d13" width="300"> | <img src="https://github.com/quarto-dev/quarto/assets/58906128/cb217740-4f89-4978-b532-9199a0fa826a" width="300"> |
| <img src="https://github.com/quarto-dev/quarto/assets/58906128/01125b73-2260-487e-a4af-03ae44b56332" width="300"> | <img src="https://github.com/quarto-dev/quarto/assets/58906128/42693d51-ae37-4178-88fc-4ad7447bca4a" width="300"> |

When editing in source mode, this issue is not observed. Any work on improving the situation with visual editor (ideally to match the colours used in source mode) would be much appreciated!

_Quarto VS Code Extension v1.94.1_

Thanks,
digg33

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here https://github.com/quarto-dev/quarto/commit/9b2e9dc8937241e224ab5b591950a4d74cc77d2d and is available in our updated release (v1.95.0)
