### ISSUE TITLE
VS Code Quarto extension: Make 'Toggle Line Comment' create a triple-dash comment `<!--- --->`

### ISSUE THREAD

**Issue by allefeld** [quarto-dev/quarto#252]
In VS Code, when editing a `qmd` file, the editor action 'Toggle Line Comment' (`editor.action.commentLine`, bound to Ctrl+Shift+7) creates a language-appropriate comment when inside a code block, and an HTML comment `<!-- -->` when outside. So far so good.

However, I noticed that code blocks within an HTML comment are not excluded from execution, and a triple-dash comment `<!--- --->` is necessary to achieve that, see https://github.com/quarto-dev/quarto-cli/issues/696#issuecomment-1103795774. I think it would be better if 'Toggle Line Comment' creates a triple-dash comment, because when I comment out a piece of code (in this case, a piece of document containing code) I expect that code not to be executed.

***

In case you prefer not to make this change – can you let me know how to achieve that effect myself? Here's my attempt:

In `quarto.json`:
```json
	"Quarto Comment Out": {
		"prefix": "<!",
		"body": [
			"<!---",
			"${TM_SELECTED_TEXT}",
			"--->",
		],
		"description": "Comment out with triple-dash HTML comment"
	}
```

In `keybindings.json`:
```json
    {
        "key": "ctrl+shift+7",
        "command": "editor.action.insertSnippet",
        "args": {
          "name": "Quarto Comment Out"
        },
        "when": "editorTextFocus && editorLangId == quarto"
    }
```

The problem with this is that while it works in the main document text, a side effect is that the same keybinding within code blocks is disabled. I tried to fix that by making the when-clause `"editorTextFocus && editorLangId == quarto && !isInEmbeddedEditor"`, but with no luck.

**Comment by allefeld** [comment]
I'm afraid I misunderstood https://github.com/quarto-dev/quarto-cli/issues/696#issuecomment-1103795774, I thought it was existing functionality when it actually was only a suggestion.

**Comment by allefeld** [comment]
I'm afraid I misunderstood https://github.com/quarto-dev/quarto-cli/issues/696#issuecomment-1103795774, I thought it was existing functionality when it actually was only a suggestion.

**Comment by jjallaire** [comment]
@allefeld I just made this change here: https://github.com/quarto-dev/quarto/commit/0fa24300b353446c46a1e48660f8cf1bae32d2cb

Note that triple-dash is meaningful (as compared to double dash) to Pandoc, in that triple dash delimited comments are excluded entirely from the output whereas double-dash comments are included in HTML output.

Note that the code is indeed still executed. @cscheid given that pandoc has this behavior (albeit poorly documented) should we consider eliding triple-dash delimited comments entirely from execution?

**Comment by cscheid** [comment]
@jjallaire that would make us more consistent with Pandoc, but less consistent with knitr.

I like that idea. I note that we have planned on a "pre-engine Pandoc pass" for a while, and that would automatically mean that triple-dash delimited comments will be hidden from engines. Should we wait for that or should we add this as a special case?

**Comment by allefeld** [comment]
Thanks @jjallaire!

According to https://github.com/quarto-dev/quarto-cli/discussions/3330#discussioncomment-6823919 we can expect corresponding behavior from the `quarto render` & Co.  in the not-too-distant future.

**Comment by cderv** [comment]
> Note that triple-dash is meaningful (as compared to double dash) to Pandoc, in that triple dash delimited comments are excluded entirely from the output whereas double-dash comments are included in HTML output.

I don't know if I am too tired, but I am going crazy as I can't make this syntax  `<!---`  works with Pandoc. 

> pandoc has this behavior (albeit poorly documented)

I can't find anything on it really - except some discussion and proposal about this, but no implementation. I found this old discussion https://groups.google.com/g/pandoc-discuss/c/FnTRTIhCEi4 and more recent https://github.com/jgm/pandoc/issues/7762

What I am missing ? I just wanted to try as I was not aware of this behavior at all.
