### ISSUE TITLE
autocomplete not working starting with v.1.95.0

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto#253]
This may be related to #246, but I am having problems getting autocomplete to work for Python. I am on MacOS, using VS Code v1.81.1.

I hope screenshots can be useful, in absence of a full reprex:

---

v1.95.0

<img width="645" alt="CleanShot 2023-08-25 at 15 53 42@2x" src="https://github.com/quarto-dev/quarto/assets/2800934/705f861f-d6fc-44b4-91f5-a5dfd90b7fee">

---

v1.94.0

<img width="583" alt="CleanShot 2023-08-25 at 15 46 44@2x" src="https://github.com/quarto-dev/quarto/assets/2800934/0d98bbe8-8a82-4462-9c0c-c8dbee375489">

**Comment by jjallaire** [comment]
It almost certainly is related to that "fix". I'll back it out and republish the extension.

**Comment by ijlyttle** [comment]
Thanks!

**Comment by jjallaire** [comment]
Thanks for reporting this so promptly! Just published v1.95.1 which reverts that fix.

**Comment by ijlyttle** [comment]
No worries, it was a bit of dumb luck that pushed me from `.ipynb` to `.qmd` at just that time :)

Autocomplete is working for v1.95.1, so I am happy to close this
