### ISSUE TITLE
Bad highlight of json codeblocks in VS Code

### ISSUE THREAD

**Issue by FabienSe** [quarto-dev/quarto#260]
Hello,

The highlight of json codeblocks seems not working in VS Code with `{.language}` syntax.

With the following code, its is working:

`````code
```json
{ 
    "name": "Under Alarm",   
    "bits": 1 
}
```
`````

But the following code which should be equivalent, it is not working:

`````code
```{.json}
{ 
    "name": "Under Alarm",   
    "bits": 1 
}
```
`````
I also tried to use other identifiers of json language:
- `json5` is also not working
- But all `sublime-*` are working! Which is really strange to me.

If I am trying the same syntax with for other languages (plantuml, clojure) the two syntaxes are working. 

So something seems broken with `json` and `json5` identifiers .

Thanks for your help!

#### Configuration 
Tests realized on windows 10 and VScode `1.82.0` with VS Code extension `v1.97.0`
Quarto information:
```console
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252
```

**Comment by jjallaire** [comment]
Thanks so much for reporting this!!! I sorted out the problem and it should be fixed here: https://github.com/quarto-dev/quarto/commit/0a78c225a2e141994aec0b3e99e83d62ebec77c0 (not yet available in a published release but will be in a week or two)
