### ISSUE TITLE
Support interactive dev of quarto books (= multifile file report) in VS Code

### ISSUE THREAD

**Issue by chamaoskurumi** [quarto-dev/quarto#262]
I would like to author a  [quarto book](https://quarto.org/docs/books/) in VS Code using Python.
When I do "Quarto: Create Project" --> "Book Project" --> enter dir name - a book template is created as expected.

![image](https://github.com/quarto-dev/quarto/assets/7808560/224c0c38-0d4e-4ecb-b669-7d4df7c90ed7)

When I create Python Code Cells in the `intro.qmd` and want to send it to the REPL interactively via  ctrl+Enter or via 
![image](https://github.com/quarto-dev/quarto/assets/7808560/506f2f44-fc90-4026-ba8b-462df0451159)

The code will not be exectued in the REPL:

![image](https://github.com/quarto-dev/quarto/assets/7808560/4d7d70c3-e536-48f4-baf5-2a239144d0fa)

Apparently the kernel or the engine is not found (because the yml header lives in a seperate `_quarto.yml` file?). 

Is there a way you can add support for interactive authoring (= enabling sending code cells to the REPL) for quarto books in VS Code please?

### Sys info

Quarto 1.3.433
VS Code Quarto Extention v1.97.0
Pop!_OS 22.04 LTS

**Comment by jjallaire** [comment]
There aren't any known problems with Quarto books and code execution. The error you are seeing appears to be with the Python Interactive Window (and I haven't unfortunately seen that error before!)

**Comment by chamaoskurumi** [comment]
Ok so when you add a simple python code cell to `intro.qmd`, then you click on "Run Cell", the interactive Window opens as expected and executes the code?

````python

```{python}
1+2
```
````

**Comment by chamaoskurumi** [comment]
It was indeed a problem on my side.
My VS Code extentions were messing up python environment selections for the Jupyter Kernel. My bad. 
This issue can be closed.
