### ISSUE TITLE
vscode go to definition or rename not working

### ISSUE THREAD

**Issue by mihem** [quarto-dev/quarto#267]
Hi,

here @jjallaire implemented go to definition in vscode, which is super handy.
https://github.com/quarto-dev/quarto/issues/60 

Unfortunately does not work for me with the latest Quarto version:

![image](https://github.com/quarto-dev/quarto/assets/46907494/836ede32-5012-4170-9d5c-14231cb73a1b)

In .Rmd files this works.
Quarto version: 1.98.0

Also there;s no `Rename Symbol` when doing a Right Click (while this does exist in .Rmd files).

Thank you!

**Comment by jjallaire** [comment]
Thanks for reporting this! This is addressed here: https://github.com/quarto-dev/quarto/commit/52ff7b98da2ac83f9a29e34b4379334b4e9ea642 (not yet available in the published extension, should be within a week or two).

Note that we indeed do not implement Rename Symbol for Qmd (the implementation for Rmd comes from the R VS Code extension not the Quarto Extension)

**Comment by mihem** [comment]
@jjallaire  thanks for this super fast reply, and the fix .. and just all your great work on R.

Any chance that renaming symbols will be implemented? I think that would be an important feature.

**Comment by jjallaire** [comment]
Renaming symbols is definitely something we'd like to do but just haven't been able to set aside the time (visa vi all of the other things we have in our backlog)

**Comment by mihem** [comment]
@jjallaire Sorry to necrobump, but `go to defintion` does not work for me in in VS Code with Quarto v1.115.0. It worked fine in v.1.98.0. I haven't used Quarto for a while so not sure when exactly this broke.

Thanks!
