### ISSUE TITLE
Format selection/document no longer working for R code

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto#270]
It appears, since v1.95.0, it is no longer possible to format R code inside a Quarto document.

See example in https://github.com/mcanouil/quarto-lintr available via Codespace.

https://github.com/quarto-dev/quarto/assets/8896044/335d0cb9-41c3-4826-97fb-8a3c722e5452

**Comment by jjallaire** [comment]
Yes, we removed this behavior as part of overhauling code formatting to be safer (we found that race conditions with the R extension could sometimes cause code to be lost during formatting!). Currently the only gesture available is really "Format Cell" ("Format Document" still works but it resolves to "Format Cell", and "Format on Save" will format the cell where the cursor is during save.

**Comment by mcanouil** [comment]
Then the code language detection is sometimes off, I'll try to make an example.
We faced cases where some R code cells were not formatted while formatting the whole document via the extension context menu.
Currently, from the R user point of view, no linting and kind of no formatting (formatting selection is more used than other forms) is a real bummer. 😔
(Side note: I currently did not figure out what exactly triggers that behaviour, but sometimes R code is not sent to the terminal as a block but line by line, once I figured out a reproducible example, I'll share that separately)

**Comment by mihem** [comment]
Agree. Formatting and linting are essential.

**Comment by jjallaire** [comment]
Linting wasn't something we ever supported (I think we could in concept though).

With formatting entire documents, the problem is that for very large documents the formatter is slow enough that race conditions between the R extension and Quarto exist where lines of code can be deleted! I realize its inconvenient to only be able to format a cell at a time but the alternative is that some users will lose data.

**Comment by mihem** [comment]
Understood.

But then the user will maybe avoid quarto and look for alternatives, which is a shame because quarto has some many advantages compared to rmarkdown or others.

**Comment by jjallaire** [comment]
I just released v1.99.0 which restores all of the previous formatting behavior (I found the issue behind all of the previous robustness problems and resolved it)

**Comment by mcanouil** [comment]
Thank you, this is amazing!
This is going to make many people happy.

**Comment by mihem** [comment]
Great work.
