### ISSUE TITLE
VSCode: quarto render and quarto preview behavior differ from cli

### ISSUE THREAD

**Issue by chendaniely** [quarto-dev/quarto#271]
Currently the VSCode extension for quarto does not have a `Quarto: Preview` command, only a `Quarto: Render`.

When running `Quarto: Render` the VSCode terminal shows:

```
$ quarto preview /Users/danielchen/git/rstudio/quarto-intro_examples/example-01-code_chunks.qmd --no-browser --no-watch-inputs

# stuff
# stuff
# stuff

Watching files for changes
Browse at http://localhost:5579/
```

This is a bit confusing since the output appreas to be running `quarto preview`.

According to JJ:

> It does both. It runs Quarto Render on the current file and previews it. There is a separate Quarto: Render Project command if you want to make sure to re-render all of the files

The issue I am having is the bahaviour is different from the CLI, especially where I expect to get a command prompt back when running `quarto render` and have the terminal locked up when running `quarto preview` as it looks for file updates.

If it's possible to rename the current `Quarto: Render` command to `Quarto: Preview` and create a separate/new `Quarto: Render` command it would make things more consistant with the CLI, and potentially less confusing to folks using Quarto with VSCode.

**Comment by jjallaire** [comment]
PR to resolve this here: https://github.com/quarto-dev/quarto/pull/273
