### ISSUE TITLE
All preview formats but html no longer available for .ipynb or .qmd files in after update to 1.100.0

### ISSUE THREAD

**Issue by codyish** [quarto-dev/quarto#278]
### Bug description

The preview (previously render) option no longer has any format option other than html. When I select the "Preview format..." option I can only select "format: html"

![2023-09-26_16-28](https://github.com/quarto-dev/quarto-cli/assets/16812640/fa730e50-c244-446f-9a45-1a70a16925cc)

Reverting to 1.99.0 restores all format (for what it's worth I also preview having all the format options available under the UI dropdown, it's a lot fewer clicks.)

### Steps to reproduce

This happens in all of my notebooks and .qmd files.

### Expected behavior

I should find some way of generating a .pdf or .docx preview.

### Actual behavior

I don't have those options, I can only do the html live preview.

### Your environment

VS code - 1.82.2
MacOS - 12.6.6

### Quarto check output

```zsh
Quarto 1.4.386
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.386
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/codystephenson/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /Users/codystephenson/opt/anaconda3/bin/python
      Jupyter: 4.9.2
      Kernels: ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```

**Comment by codyish** [comment]
Sorry - I had too many tabs open and got lost and initially submitted this to the -cli repo.

**Comment by jjallaire** [comment]
Yes, we just made a change to only show the formats declared in the document. The positive of this is that ALL formats (including custom formats) are now supported. The downside is no automatic docx and pdf --- perhaps we should put those back in?

In the meantime, you can do something like this to get those back into the menu:

```yaml
---
format: 
    html: default
    pdf: default
    docx: default
---
```

**Comment by codyish** [comment]
Ahh, I see. It seems like having PDF as a default could be good from a UX perspective, but now I get the new workflow. Unfortunately, this has uncovered a new issue - now it works in .qmd but I can't get anything to work with .ipynb - I get a "No quarto document available to render" error. Should I open a new issue?

**Comment by jjallaire** [comment]
Interesting! Either `markdown` or `raw` should actually work for the front matter cell. If you have a repo that has a reproducible case for not being able to render an ipynb please share it and we will investigate further!

**Comment by jjallaire** [comment]
Just published version 1.101.0 of the Quarto Extension to the Marketplace --- this restores the format-specific commands using the new terminology ("Preview HTML", "Preview DOCX", etc.). The "Preview Format..." command can still be used to pick any format declared within document or project options.

**Comment by codyish** [comment]
> Interesting! Either `markdown` or `raw` should actually work for the front matter cell. If you have a repo that has a reproducible case for not being able to render an ipynb please share it and we will investigate further!

This notebook gives me trouble - https://github.com/codyish/Prob_class_series/blob/main/probHW1.ipynb

Other ones I create don't always do it. It's so weird - switching to raw and clicking "preview" work instantly, switching it back to markdown and saving and clicking preview says "no quarto document found"

**Comment by jjallaire** [comment]
Interesting, that notebook is working fine for me locally (both in raw and markdown mode).

**Comment by codyish** [comment]
So strange - since it's not all of my files and it's an easy fix it's very low priority for me, so if I ever happen to figure out what is causing it and how to reproduce it I'll post it. Thanks for all the attention and quick responses.
