### ISSUE TITLE
Integration with code spell checker

### ISSUE THREAD

**Issue by Lightup1** [quarto-dev/quarto#29]
For writing, spell checker is a quite useful tool. But Quarto extension in vscode is not integrated with a spell checker.
In #1218 , one has proposed a solution to use code spell checker extension, which eases the problem to some extent but still has some unsatisfactory points. For example, if one specifies .qmd with quarto spell checker, it will check all the contents of .qmd file. But in most cases, one only needs to check markdown cells, which contain contents for publishing. 
So it will be good that quarto extension itself can support markdown cell spell checking.

**Comment by jjallaire** [comment]
@harrelfe Just a note that Spell Right now automatically recognizes and checks `qmd` files (so no special config should be required).

Also note that the Quarto Visual Editor (first seen in RStudio) is now available in VS Code -- the visual editor does support spell checking.  We haven't yet implemented code completion or cell execution but plan to soon. Details are here: https://quarto.org/docs/visual-editor/vscode/

**Comment by Lightup1** [comment]
@jjallaire I have to say that Visual Editor is amazing!
