### ISSUE TITLE
Conflict with other open ipyn notebooks

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto#3]
Steps to reproduce the problem:

1. Open a `qmd` file on a newly opened VS Code instance and render the document.
2. Open a new  VS Code instance (not a new window, but a new instance).
3. Open a `ipyn` notebook and edit it.
4. When clicking on save button of the `ipyn` notebook, VS Code will render the `ipyn` notebook.

Thanks in advance!

**Comment by jjallaire** [comment]
Okay, I can reproduce with the steps you provided. Thanks!

**Comment by jjallaire** [comment]
Thanks again for reporting this. It's fixed here (https://github.com/quarto-dev/quarto/commit/8835d34f1019eb2af5c24d435aadce8e52bb9434). This will be in our next release (out sometime over the next week or two)
