### ISSUE TITLE
VS Code: Improve visibility of horizontal rule in high contrast themes

### ISSUE THREAD

**Issue by digg33** [quarto-dev/quarto#301]
Hello devs,

Thank you for your work on this project. Currently, the VS Code extension does not display horizontal rules in visual mode with either of the high contrast themes shipped with VS Code. It would be much appreciated if the visibility of the rule could be improved for these themes.

Thanks,
digg33

**Comment by jjallaire** [comment]
Thanks for the feedback! This should be taken care of here: https://github.com/quarto-dev/quarto/commit/dea0acb7adfec47eddd3265506d2e36d94d40e6d
