### ISSUE TITLE
verifyInstallation in the VSCode plugin gives confusing error when quarto not found

### ISSUE THREAD

**Issue by ChrisJefferson** [quarto-dev/quarto#304]
In the quarto vscode plugin, any command I try to run results in an error message, for example for verifyInstallation I get a popup that says:

Command 'Quarto: Verify Installation' resulted in an error
command 'quarto.verifyInstallation' not found

I tried opening the vscode debugging window, and get the following error at the end, but this doesn't mean a lot to me.

```
mainThreadExtensionService.ts:113 Activating extension 'quarto.quarto' failed: Invalid Version: .
$onExtensionActivationError @ mainThreadExtensionService.ts:113
S @ rpcProtocol.ts:456
Q @ rpcProtocol.ts:441
M @ rpcProtocol.ts:371
L @ rpcProtocol.ts:297
(anonymous) @ rpcProtocol.ts:161
z @ event.ts:1138
fire @ event.ts:1169
fire @ ipc.net.ts:650
Y.onmessage @ localProcessExtensionHost.ts:581
```

I assume the plugin does work for other people, so I've done something wrong. My vscode doesn't show any other strange problems, and I'm open to debugging suggestions.

**Comment by ChrisJefferson** [comment]
I've figured out my issue (although I think it still needs fixing?)

Running 'verifyInstallation' when quarto is not in the path produces the error I show above (I assumed 'verifyInstallation' might give me some more useful "quarto not found" type error?)

I can then go into the settings, set the location of quarto, and get the same error (as I guess the package doesn't get reloaded when I change the settings?)

If I then exit vscode entirely and reload it, then verifyInstallation, and everything else, works fine.

**Comment by jjallaire** [comment]
Thanks! We will create a much better error message/experience for this situation.

**Comment by jjallaire** [comment]
Thanks again for reporting this, should be addressed here: https://github.com/quarto-dev/quarto/commit/d23c760514e81c6c5d2d521fbd97ed74912dabe2
