### ISSUE TITLE
`\mathcal{I}` Renders different than from Rstudio IDE

### ISSUE THREAD

**Issue by jtlandis** [quarto-dev/quarto#306]
This is a minor issue that I have run across and I am unsure if this is the correct repository to post to.

Consider this reprex

````qmd
---
title: "test"
format: pdf
editor: visual
---


$$
\mathcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ}(\theta)
$$


````

Here I show the alphabet under the `\mathcal` latex command. The IDE preview shows the following

<img width="665" alt="Screen Shot 2023-10-19 at 9 04 37 AM" src="https://github.com/quarto-dev/quarto/assets/30324172/c63193b6-e196-4e16-85e9-4eac5541d8bf">

whereas when rendering to a PDF it looks like so:

<img width="756" alt="Screen Shot 2023-10-19 at 9 07 50 AM" src="https://github.com/quarto-dev/quarto/assets/30324172/14a1b821-8afa-4e0d-9c15-2e086dbcda5a">

To be honest, most of the letters have a different rendering font than the preview, But I'm inclined to say that`\mathcal{I}` looks more like a J when rendered than in the preview.

I was cross comparing latex symbols [here](https://latex-programming.fandom.com/wiki/List_of_LaTeX_symbols) and I noticed that the rendered `\mathcal{I}` looks more like the `\mathcal{J}` from the linked resource.

**Comment by jjallaire** [comment]
Yes that's xelatex rendering (in the pdf) vs. mathjax rendering (in the editor). Two completely different codebases so unfortunately there may be some variation.
