### ISSUE TITLE
Shouldn't preview watch inputs?

### ISSUE THREAD

**Issue by postylem** [quarto-dev/quarto#307]
When previewing a file in VSCode, it seems odd to me that the preview doesn't update as the file is edited. 
Especially since the output from the command `quarto preview my_file.qmd --port=3333 --no-watch-inputs` prints the message **`Watching files for changes`** (which may be a separate quarto issue... it _isn't_ watching for file changes, right?).

The flag could be removed to make the preview auto update. Is there a good reason not to make this change?

https://github.com/quarto-dev/quarto/blob/658dad57be28765f8a52a654ae331d01bc1e9e4a/apps/vscode/src/providers/preview/preview.ts#L477

**Comment by jjallaire** [comment]
This is because for some users **Render** takes a long time (many minutes) and having this occur automatically is quite unfriendly (especially to battery life!). There are lots of ways to customize this though so you can get the behavior you want: https://quarto.org/docs/tools/vscode.html#render-on-save

BTW it is still watching files for changes (just not the input `.qmd`, it is watching e.g. CSS files which require only a lightweight browser reload).

**Comment by memeplex** [comment]
I have installed quarto for vscode for the first time just now and I have to say that this behavior confused me. I understand the rationale given by @jjallaire but:

1. The message in the terminal is:
```
Watching files for changes
Browse at http://localhost:7194/
```

2. Even if the message weren't wrong, keeping the process running doesn't make sense if the goal is to produce just one output, and doing so is certainly misleading.

**Comment by memeplex** [comment]
Ok, now I realize that `--no-watch-inputs` is not incompatible with `Watching files for changes`, because the latter is referring to outputs, not inputs, and setting `renderOnSave` will make everything work. But as a newcomer, I insist in that my first impression was of confusion.

**Comment by memeplex** [comment]
No, there is something else going on.

From the command line whether I pass `--no-watch-inputs` to `quarto preview` or not, it outputs `Watching files for changes` at the bottom. But in the first case it isn't actually watching for changes, nothing happens after I change and save a file. So this cannot be explained away by a difference between watching inputs or output, as I did before. I believe the message at the end is wrong, it's not taking into account the no-watch flag.

Now, if from vscode I press the preview button, no matter the value of `renderOnSave` the launched command *always* include `--no-watch-inputs` (as it shows at the top of the Quarto Preview terminal). But the behavior when `renderOnSave` is set is as if `--no-watch-inputs` hasn't been passed to the command.

So I'm actually more confused than at the beginning.

**Comment by dragonstyle** [comment]
- I think the message is just wrong: If I recall correctly, there were tools which were monitoring the output of `preview` and using the `Watching files for changes` as a signal that the preview server was running, so we end up outputting the message whether or not we are truly watching files.

- `renderOnSave` actually triggers a render of the document, which alter the output (causing the preview to reload). The reloading isn't really triggered by the input change, but by the output changing.

- I definitely don't disagree that this has been a source of confusion though I think it represents a compromise to make things work for many / most cases (and stay compatible with tools that are moving more slowly than Quarto).

**Comment by memeplex** [comment]
Or perhaps I was right about the input/output distinction and `Watching files for changes` always means `Watching output files for changes` but when not passing `--no-watch-inputs` it also means `Watching input files for changes`.
