### ISSUE TITLE
Visual Mode “executes” HTML-Code and writes plain text in source file instead of leaving it unchanged 

### ISSUE THREAD

**Issue by Pindar777** [quarto-dev/quarto#308]
I tried for the first time the new visual mode of Quarto.
It is a great add-on, however, at the moment there is a major caveat for me: 

Important formats like  `&nbsp;`or  e.g. `&bdquo;Models&ldquo;`

are rewritten to plain text. In case of the apostrophes the change leads to design errors:
„Models" instead of &bdquo;Models&ldquo;

I encountered the issue on Windows as well as on MacOS, in VSCode and RStudio desktop.

**Comment by jjallaire** [comment]
Thanks for reporting this! It should be handled with this commit: https://github.com/quarto-dev/quarto/commit/4d731797a79f193160898c7a4a82a8cd04446ac9

Release with this fix will be available early next week.

**Comment by Pindar777** [comment]
@jjallaire Thank you for the fast patch.
