### ISSUE TITLE
option to publish 2 slidedecks from same folder?

### ISSUE THREAD

**Issue by pvgenuchten** [quarto-dev/quarto#319]
hi, when i have a single slides .qmd in a folder, publish works fine, but when i have 2 qmd's in that folder quarto publish fails with: 

```
$ quarto publish gh-pages ./slides --no-render --no-browser
ERROR: The specified path (./slides) is not a website or book project so cannot be published.

Stack trace:
    at createPublishOptions (file:///opt/quarto/bin/quarto.js:105064:19)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async publishAction (file:///opt/quarto/bin/quarto.js:104977:28)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:104972:9)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8111:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:111631:5)
    at async file:///opt/quarto/bin/quarto.js:111649:9
```

**Comment by jjallaire** [comment]
When there is more than one `.qmd` in a directory you need explicitly specify which one you want to publish, e.g.

```bash
quarto publish gh-pages ./slides/slides.qmd --no-render --no-browser
```

**Comment by pvgenuchten** [comment]
Thanx, there is no option to publish all of them at once?

**Comment by jjallaire** [comment]
You could create a website project and then all of them would be published.

J

**Comment by pvgenuchten** [comment]
Great, this works super!
- website project, index page to all decks
- Each slide deck: format: revealjs



https://github.com/pvgenuchten/slides

thanx for support

**Comment by jjallaire** [comment]
Great! So glad we got a configuration that works well. To run up the score slightly you might consider making the home page a document listing (https://quarto.org/docs/websites/website-listings.html)
