### ISSUE TITLE
Provide other computational engine options in "Insert Code Cell"

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto#32]
"Quarto: Insert Code Cell, Control+Shift+I" is fixed with R. Could we provide other computational engine options when inserting a new code cell?

**Comment by jjallaire** [comment]
I don't currently see an API that will let us pop a menu up here so I am going to close the issue (feel free to re-open if you become aware of a way for us to add this menu)

**Comment by jooyoungseo** [comment]
@jjallaire -- What about implementing this via a snippet and assigning the current keybinding like this: https://github.com/REditorSupport/vscode-R/blob/master/snippets/rmarkdown.json?plain=1#L116-L122

**Comment by jjallaire** [comment]
@jooyoungseo That's a great idea! Will re-open and implement this soon.

**Comment by jjallaire** [comment]
@jooyoungseo This implements the behavior you suggested: https://github.com/quarto-dev/quarto/commit/7dc4310f1e61f7cb539b24d3589b0bdeeef9cdaa

Should be released in a new version of the extension within a few days.
