### ISSUE TITLE
section numbering not working well with HTML hX

### ISSUE THREAD

**Issue by neonira** [quarto-dev/quarto#323]
Apparently, Quarto does not take into account inline HTML h1, h2, ... when dealing with numbering sections ... Weird ... 

[source code ](https://github.com/quarto-dev/quarto/files/13295945/html-sections.log) was .qmd file, renamed to .log extension to enable attachement here

Screenshot of the results I got ![Screenshot of the results I got](https://github.com/quarto-dev/quarto/assets/37214634/11e89245-f4c2-4412-9372-4ff98cd8f66f)

environment used ![environment used](https://github.com/quarto-dev/quarto/assets/37214634/29011c8e-99ed-4d27-b44b-0c53082cf6e8)

**Comment by cderv** [comment]
This is a pandoc behavior IMO. Section numbering works only on the Markdown Header parsed as Header in the AST. 

When you provide `<h1>` as HTML it is only seen as Raw HTML by Pandoc parsing , and thus Quarto. The raw block can be anything, and they are not parsed in the AST. 

Thus the section numbering will not apply, as it applies only on Header through AST processing. 

<details>
<summary>Pandoc to native conversion </summary>

````
$ pandoc -t native
<h1 class="mytitle">ABC</h1>

<h2 class='mytitle2'>L2</h2>

<h1 class="mytitle">EFG</h1>

<h2 class='mytitle2'>L2</h2>

<h1 class="mytitle">HIJ</h1>

<h2 class='mytitle2'>L2</h2>

# LALA

## ZZ
^Z
[ RawBlock (Format "html") "<h1 class=\"mytitle\">"
, Plain [ Str "ABC" ]
, RawBlock (Format "html") "</h1>"
, RawBlock (Format "html") "<h2 class=\"mytitle2\">"
, Plain [ Str "L2" ]
, RawBlock (Format "html") "</h2>"
, RawBlock (Format "html") "<h1 class=\"mytitle\">"
, Plain [ Str "EFG" ]
, RawBlock (Format "html") "</h1>"
, RawBlock (Format "html") "<h2 class=\"mytitle2\">"
, Plain [ Str "L2" ]
, RawBlock (Format "html") "</h2>"
, RawBlock (Format "html") "<h1 class=\"mytitle\">"
, Plain [ Str "HIJ" ]
, RawBlock (Format "html") "</h1>"
, RawBlock (Format "html") "<h2 class=\"mytitle2\">"
, Plain [ Str "L2" ]
, RawBlock (Format "html") "</h2>"
, Header 1 ( "lala" , [] , [] ) [ Str "LALA" ]
, Header 2 ( "zz" , [] , [] ) [ Str "ZZ" ]
]
````

</details>

<details>
<summary>Pandoc and section numbering does not apply on HTML</summary>

```powershell
$ pandoc -t html -N --toc
<h1 class="mytitle">ABC</h1>

<h2 class='mytitle2'>L2</h2>

<h1 class="mytitle">EFG</h1>

<h2 class='mytitle2'>L2</h2>

<h1 class="mytitle">HIJ</h1>

<h2 class='mytitle2'>L2</h2>

# LALA

## ZZ
^Z
<h1 class="mytitle">
ABC
</h1>
<h2 class="mytitle2">
L2
</h2>
<h1 class="mytitle">
EFG
</h1>
<h2 class="mytitle2">
L2
</h2>
<h1 class="mytitle">
HIJ
</h1>
<h2 class="mytitle2">
L2
</h2>
<h1 data-number="1" id="lala"><span
class="header-section-number">1</span> LALA</h1>
<h2 data-number="1.1" id="zz"><span
class="header-section-number">1.1</span> ZZ</h2>

</details>

If I may, why use raw HTML  here ? 

If you were using Markdown, it would work as expected

````markdown
---
title: XXX
author: "Fabien GELINEAU"
date: November 2023
format: 
  html:
    embed-resources: true
    self-contained-math: true
toc: true
toc-depth: 3
number-sections: true
number-depth: 3
---


# ABC {.mytitle}

## L2 {.mytitle2}

# EFG {.mytitle}

## L2 {.mytitle2}

# HIJ {.mytitle}

## L2 {.mytitle2}

# LALA

## ZZ
````


_See here to how embed Raw code into your Github issue formatted correctly: https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us_

**Comment by neonira** [comment]
Thanks for quick and reliable feedback. 

 Understood the origin of the problem. 

Will experiment to find a solution.

**Comment by neonira** [comment]
Easiest way is to stick to pure markdown for h1, h2 and set a CSS for styling them.
