### ISSUE TITLE
Auto completion does not work properly inside R blocks

### ISSUE THREAD

**Issue by hudtorrent** [quarto-dev/quarto#329]
Hello,

Thanks for Quarto. It is amazing.

However, I am having an issue with the quarto extension in vscode.

I am using R blocks in vscode running on Debian 12. I am also using "R Editor Support" extension. The issue is that I cannot trigger the *best* completion for R. For example, the completion for .rmd files or for .r files are much better than those for .qmd files.

In this sense, I am practically forced to associate my .qmd files with r markdown (.rmd) to get proper auto completion. 

Thanks again.

**Comment by hudtorrent** [comment]
Just to give an example:

Using R markdown:
![rmarkdown](https://github.com/quarto-dev/quarto/assets/10963408/7276be3f-1f37-4918-9eb0-1e1e63da543a)

Using quarto extension:
![quarto](https://github.com/quarto-dev/quarto/assets/10963408/fa319ab5-29bb-4b1e-bd04-6ef450fb3438)

**Comment by jjallaire** [comment]
To me it appears as if completion is not working at all for embedded R chunks (those completions are actually snippet completions rather than language server completions). You might want to check the **Debug Output** tab in the panel to see if there are messages there or check the **Output** panel (selecting "R Language Server" from the picker on top). Perhaps they give some clue as to what is going on!

**Comment by hudtorrent** [comment]
Thanks a lot for your time and for the quick reply.

Looking at the Output panel ("R Language Server") I am getting the following:

completions:  {
  "init_count": 0,
  "final_count": 0,
  "time": 0.0015,
  "isIncomplete": false
}

I am not an expert, but I was wondering if it is possible to change   "isIncomplete" to true... That might solve the problem?

Cheers.

**Comment by jjallaire** [comment]
I am not at all sure how to interpret that output! It looks like it is computing "no completions available" which is indeed strange. I can't repro and this isn't widely reported so I am not quite sure what the next steps are.

**Comment by hudtorrent** [comment]
All right. Thank you very much anyway.

**Comment by thedbcooper** [comment]
I am also having unexpected behavior with suggestions/auto complete when using the Quarto language mode. I do not know how to troubleshoot, but I can edit to add software versions if that would be helpful! 

https://github.com/quarto-dev/quarto/assets/84866343/ec9de3f9-5020-420b-b3aa-992cc159d635

**Comment by eliocamp** [comment]
I can confirm that this is happening to me too.

**Comment by hudtorrent** [comment]
PauloCampana made an observation above that seems to be correct (https://github.com/quarto-dev/quarto/issues/437).

Indeed, I have a machine with the problem we are talking about here and another machine where things work correctly.
On the machine where things work fine the file ".intellisense.r" is located at "/.local/share/Trash/files".

Can we change where the intellisense file is created and fix the problem?

By the way, in the machine where things work fine I have only one HD. In the machine with the problem I have two HD's (one SSD with the system files and a non-SSD with /home partition). Is there any chance this is causing the problem?
