### ISSUE TITLE
Snippets Support

### ISSUE THREAD

**Issue by joel-beck** [quarto-dev/quarto#33]
Currently, `editor.action.triggerSuggest` does not suggest user snippets, neither global snippets from `global.code-snippets` nor language-specific snippets from`quarto.json`.

It would be awesome to support context-aware snippets such that existing snippets from `python.json` can be used in Python code chunks, snippets from `r.json` in R code chunks, and Markdown snippets outside of code chunks to avoid snippets duplication across multiple files.

**Comment by astrowonk** [comment]
Yikes, yeah I was trying to figure out why my snippets don't work as I wanted to make some for calloutblocks and ran into this. The snippets, they do nothing...

**Comment by jjallaire** [comment]
This is resolved here: https://github.com/quarto-dev/quarto/commit/a038849f35a2d78cfd8ffc54e94c5961b077b885

v1.110.0 release that includes this fix will be released this week.

**Comment by jjallaire** [comment]
This is available in v1.110.0 of the extension (just published to the marketplace).
