### ISSUE TITLE
[Feature Request] More VS code Insert <something> helper functions

### ISSUE THREAD

**Issue by astrowonk** [quarto-dev/quarto#343]
The Quarto VS Code extension has a _insert code block_ option but… that's it. There's no other *Insert* anything.  I would like specifically really like _Insert Callout Block_, but I think it would also be good to have: 

* Insert Figure
* Insert Inline Python (for 1.4)
* Insert Diagram 

And probably others I haven't thought of yet!

II use call out blocks infrequently, so I always forget the syntax, it'd be lovely if I could just find it in the command palette. Any blocks that use the `:::` syntax would be nice to have inserted by VS Code.

I could use snippets? but snippets in VS Code for QUarto don't work either, see  #33

**Comment by jjallaire** [comment]
Snippets issue is resolved here: https://github.com/quarto-dev/quarto/commit/a038849f35a2d78cfd8ffc54e94c5961b077b885

You can get diagrams via the "Insert executable code" block snippet. 

v1.110.0 release that includes this change will be released this week. 

If you want to help us provide more snippets here is the source file where they are defined: https://github.com/quarto-dev/quarto/blob/main/apps/vscode/snippets/quarto.code-snippets

Note that the inline python for v1.4 might want to wait until that is formally released (as it won't work for v1.3). Insert Figure is also partly covered by the "image" snippet. v1.4 includes better support for div based figures (however again we might not want to insert those in v1.3 documents as they won't necessarily work as expected).

**Comment by jjallaire** [comment]
This is available in v1.110.0 of the extension (just published to the marketplace).

**Comment by astrowonk** [comment]
> This is available in v1.110.0 of the extension (just published to the marketplace).

I'm dazzled by how quickly this was resolved. Thanks!
