### ISSUE TITLE
Visual Editor mode fails in VS Code due to unfound pandoc 

### ISSUE THREAD

**Issue by kmasiello** [quarto-dev/quarto#344]
### Bug description

Visual Editor mode in VS Code fails with a message "Unexpected Error Loading Editor" `Request pandoc_list_extensions failed with message: spawn /Users/katie/local/share/qvm/versions/v1.4.513/bin/tools/pandoc ENOENT`
![image](https://github.com/quarto-dev/quarto-cli/assets/32964481/0886d18d-3818-456c-938d-d40aa3237f79)

Rendering the document still works.

Quarto was installed via `qvm`. Per internal discussions, another user reported similar with Quarto installed from Mamba. 

### Steps to reproduce

Install Quarto via `qvm`. 
Request Visual Editor mode in VS Code.
This may or may not be repeatable -- I'm confident I've used Visual Editor mode in VS Code previously and have always managed my Quarto versions with `qvm`.

### Expected behavior

Visual Editor mode should work.

### Actual behavior

Error message when activating Visual Mode.

### Your environment

- IDE: Visual Studio Code 1.84.2
- OS: Mac Sonoma 14.1.2

### Quarto check output

```
Quarto 1.4.513
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.513
      Path: /Users/katie/.local/share/qvm/versions/v1.4.513/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/katie/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
      LibPaths:
        - /Users/katie/Library/R/arm64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

**Comment by jjallaire** [comment]
This should be resolved here: https://github.com/quarto-dev/quarto/commit/8e1f7ecda874b62854fff697a278827a4d2046c9

v1.110.0 release with this fix will be available later this week.

**Comment by jjallaire** [comment]
This is now available in v1.110.0 of the extension (just published to the marketplace).

**Comment by clydeugene** [comment]
@jjallaire I just updated the extension to v1.110.0
<img width="631" alt="image" src="https://github.com/quarto-dev/quarto/assets/7853856/f77e469e-a6c1-476d-a8c4-25859c52d86d">

I also ran quarto check on the server to make sure all is well:

```
$ quarto check
Quarto 1.4.506
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.506
      Path: /home/cmakamure/quarto-1.4.506/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/cmakamure/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.18 (Conda)
      Path: /home/cmakamure/.conda/envs/py39/bin/python
      Jupyter: 5.5.0
      Kernels: python3, python2

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /home/cmakamure/.conda/envs/py39/lib/R
      LibPaths:
        - /home/cmakamure/.conda/envs/py39/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

My setup details are below:

**MacBook Air M1**
MacOS Sonoma 14.2.1 (23C71)

**Visual Studio Code**
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

**Remote cluster**
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by jjallaire** [comment]
I think we need to see the contents of your bin dir. Try this:

```bash
ls /home/cmakamure/quarto-1.4.506/bin/tools
```

There should be architecture specific directories there which the extension will look for if it doesn't find `pandoc`.

**Comment by clydeugene** [comment]
```
$ ls /home/cmakamure/quarto-1.4.506/bin/tools
x86_64

$ ls /home/cmakamure/quarto-1.4.506/bin/tools/x86_64/
dart-sass  deno  deno_dom  esbuild  pandoc  typst
```

**Comment by jjallaire** [comment]
Interesting, it looks like you are on an arm64 Mac however you are running an Intel version of Quarto (with no side by side installation of the Arm version which is what all of our binary installers produce). How did you obtain this version of Quarto as it looks like it doesn't have all of the requisite files?

**Comment by clydeugene** [comment]
So, I just tested VS Code on a local qmd and I can confirm that editing in both Visual and Source modes works as intended. The challenge comes when I try to edit remote files in visual mode.

**Comment by jjallaire** [comment]
Okay, the fix I initially put in targeted only the Mac (I didn't realize we had platform specific directories for Linux as well). There is a new version on the marketplace (v1.110.1) which should address this for Linux as well. Thanks for bearing with us!

**Comment by clydeugene** [comment]
Thank you so much @jjallaire, the new update fixed it for me.

**Comment by andreifoldes** [comment]
Hello - I'm using Quarto in Cursor and I think the most recent update caused the following on Ubuntu. Reverting to v1.118 fixed it however.

![Image](https://github.com/user-attachments/assets/cf17b4a4-b313-4af0-bcb6-30faea6fff9c)

**Comment by juliasilge** [comment]
@andreifoldes can you open a new discussion at https://github.com/quarto-dev/quarto-cli/discussions so we can help you get to the bottom of your problem?

**Comment by fflores97** [comment]
Working on a more general solution, motivated by NixOS not quite adhering to the above conventions. See #740
