### ISSUE TITLE
Commenting does not stop python block from executing.

### ISSUE THREAD

**Issue by yuxi-liu-wired** [quarto-dev/quarto#347]
```qmd
---
title: "Test"
---


<!-- 
\```{python}
assert False
\```
-->
```

(Sorry but I can't put triple ticks inside triple ticks here)

Gives

```
> quarto render .\index.qmd

Executing 'index.ipynb'
  Cell 1/1...ERROR:

An error occurred while executing the following cell:
------------------
assert False
------------------


---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 assert False

AssertionError:
```

**Comment by cderv** [comment]
To stop execution, you need to set `eval: false` on the cell or globally in your YAML config. 
https://quarto.org/docs/computations/execution-options.html#output-options

Commenting using HTML syntax is not something that will prevent execution. 

Also, when using jupyter engine, commenting the cell around HTML comment is not something that I think would be supported to ignore a code execution. Setting `eval: false` in the cell should work though. 

Out of curiosity, why did you expect this syntax to work ? Have you seen this shown somewhere ?

**Comment by cscheid** [comment]
I'm going to go ahead and close this one (we can keep the discussion going, but this is clearly not a bug.)
