### ISSUE TITLE
feed: true problems

### ISSUE THREAD

**Issue by joscani** [quarto-dev/quarto#348]
Hi. 
In my website https://muestrear-no-es-pecado.netlify.app/blog I generate rss feed using feed: true in blog.qmd. 

But all the links generated has wrong url.  adding `rebranding` word in each entry.  Example. in blog.xml 
The post 
https://muestrear-no-es-pecado.netlify.app/2024/01/cachitos_2023/cachitos_2023_segunda_parte
has changed his url to this : Note add rebranding word. 
https://muestrear-no-es-pecado-rebranding.netlify.app/2024/01/cachitos_2023/cachitos_2023_segunda_parte.html

Any idea.? I'm using quarto version 1.3.450 
![Captura de pantalla_2024-01-05_09-21-30](https://github.com/quarto-dev/quarto/assets/1321194/22fa31d1-b89e-4f5d-86ee-3ef41b684a13)

**Comment by cderv** [comment]
Your configuration file has `rebranding` in the site url config 
https://github.com/joscani/blog_quarto/blob/0202e90be25d2a3d4b1ef9a247d2a6bb2e3623f1/_quarto.yml#L11
```yaml
  site-url: https://muestrear-no-es-pecado-rebranding.netlify.app/
```

And this configuration is used in RSS feed as explained in the doc: https://quarto.org/docs/websites/website-blog.html#rss-feed

Wrong config ?

**Comment by joscani** [comment]
ups. yeah. 
Thanks. My fault
