### ISSUE TITLE
[Feauture request] WYSIWYG markdown editor framework

### ISSUE THREAD

**Issue by camilogarciabotero** [quarto-dev/quarto#35]
Hi all,

Thank you for all your work on this extension for quarto. I just spotted [Milkdown](https://github.com/Saul-Mirone/milkdown) a nice WYSIWYG markdown editor framework, thought it could be a nice feature for adapting the quarto-vscode extension.

Best.

**Comment by jjallaire** [comment]
@camilogarciabotero We have now integrated the visual editor into the VS Code extension. We haven't yet added support for cell execution and completion (but will soon). Details are here: https://quarto.org/docs/visual-editor/vscode/

**Comment by camilogarciabotero** [comment]
Yes! I've been using it for a couple of days, which is fantastic. Thank you for working on this project.
