### ISSUE TITLE
Choose R kernel in VS Code

### ISSUE THREAD

**Issue by royfrancis** [quarto-dev/quarto#358]
In VS Code, When an ipynb notebook is opened, there is an option in the top right to choose the Python kernal. This gives me the flexibility to choose from the various virtual environments and conda environments that I have.

![Screenshot 2024-01-17 at 18 16 44](https://github.com/quarto-dev/quarto/assets/5083500/cdde2935-312b-4fc4-8d8e-164cb2405d2e)

How do I choose which Python or R to use in a quarto document?

```
VS Code 1.85.1
Quarto extension: v1.110.1
```

**Comment by jjallaire** [comment]
If you use the **Python: Select Interpreter** command (which sets the default Python for the current workspace) then Quarto will follow the version of Python specified there.

**Comment by mcanouil** [comment]
Additionally, one can use `_environment` (<https://quarto.org/docs/projects/environment.html>):

```txt
QUARTO_PYTHON=/path/to/bin
QUARTO_R=/path/to/bin
```

**Comment by royfrancis** [comment]
I assume you are talking about rendering a quarto document in the terminal. I was asking about interactively working in a quarto document in VS Code using the quarto extension.
