### ISSUE TITLE
Support more render targets

### ISSUE THREAD

**Issue by asmaier** [quarto-dev/quarto#36]
At the moment the plugin only allows to render

- html
- pdf
- word

But according to https://quarto.org/docs/output-formats/all-formats.html there are many more formats available.

I personally would like to also have OpenOffice and PowerPoint, but maybe a dropdown can be added, so one can select from the list of available formats.

**Comment by jjallaire** [comment]
If you switch the default (topmost) format within the qmd file then the render command (and shortcut) will target that format, e.g. you can do:

```yaml
format: revealjs
```

And that will render Revealjs (same for PowerPoint, etc.). 

The VS Code extension API is unfortunately not dynamic for editor menus so its not possible for us to add all of the formats there.
