### ISSUE TITLE
Latex math does not render correctly

### ISSUE THREAD

**Issue by dmitryhits** [quarto-dev/quarto#365]
The latex math does not render correctly with quarto extension.
For example, 
'$p_f$  is the final pressure'
renders as: 
![image](https://github.com/quarto-dev/quarto/assets/6305029/0137eaec-d0d9-477c-ac00-8da57b776f04)

I am running Ubuntu 22.04.3 LTS on Windows LWS
jupyterlab                4.0.12             
jupyterlab-quarto         0.2.8

Is there a fix for this?

**Comment by cderv** [comment]
Do you mean in VSCODE visual mode ? 
It shows ok for me both in editor mode, and in HTML preview of the rendered output

![image](https://github.com/quarto-dev/quarto/assets/6791940/a6540de2-b36f-4693-9abe-93db0490ee2f)

Can you give more context and information ? 

Are you referring to JupyterLab extension maybe ? (guessing from reference to `jupyterlab-quarto 0.2.8`) ? 

This repo is about several of editor and Quarto extension, so it would help to have more detailed information.

**Comment by dmitryhits** [comment]
Yes, sorry. I am referring to the jupyterlab extension. Someone already opened a similar issue[ there](https://github.com/quarto-dev/jupyterlab-quarto/issues/3#issue-2116435203) with a lot more details. I guess we can close this one?
