### ISSUE TITLE
Run code button missing in Python cells in Visual mode for VS Code

### ISSUE THREAD

**Issue by malcolmbarrett** [quarto-dev/quarto#384]
As discussed in https://github.com/quarto-dev/quarto-cli/discussions/8807, it appears that when editing in Visual mode, python cells are missing the run code button

**Comment by jjallaire** [comment]
That's unfortunately a limitation of the VS Code Jupyter extension we use to execute Python cells (you have to have text editor active and visual editor is not that!)

**Comment by malcolmbarrett** [comment]
whoa, what a bummer limitation! I hope that changes upstream. I'm not sure if I'll teach the visual editor for this context.
