### ISSUE TITLE
VSCode Extension: "Executing python cells requires the Jupyter extension." 

### ISSUE THREAD

**Issue by heygent** [quarto-dev/quarto#385]
Trying to run a cell in a qmd file doesn't work, and gives the notification "Executing python cells requires the Jupyter extension.". Jupyter extension is installed and working with ipynb files.

Running macOS Sonoma 14.2.1.

<img width="1335" alt="Notification screenshot" src="https://github.com/quarto-dev/quarto/assets/11190881/279b176d-f8f9-4efb-91ad-997435ccc5c1">

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /Users/gent/.pyenv/versions/3.12.1/envs/tesi/bin/python3
      Jupyter: 5.7.1
      Kernels: loball, tesi, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by skwde** [comment]
Same with `1.4.553`:

```sh
Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.9
      Path: /usr/local/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
Could you both confirm that you have the VSCODE Jupyter Extension : https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

The message in VSCODE refers to the Jupyter Extension as a VSCODE Extension like Quarto Extension, and not just the Jupyter module from pip installed your selected Python version. 

Thanks

**Comment by skwde** [comment]
Thanks for your immediate reply.

Yes it is indeed working when the jupyter extension is installed.

VSCode asked me to install the python extension `ms-python.python` but not the jupyter extensions `ms-toolsai.jupyter`.

Besides that since this seems to be a dependency for https://quarto.org/docs/get-started/hello/vscode.html it should be mentioned there. 

Is there a list somewhere which extensions are required in which case?

**Comment by cderv** [comment]
> Is there a list somewhere which extensions are required in which case?

This is mentioned there: https://quarto.org/docs/tools/vscode.html#code-cells 

but it seems Jupyter extension is missing. It is mentioned in Python extension doc : https://marketplace.visualstudio.com/items?itemName=ms-python.python#jupyter-notebook-quick-start

We could probably add it to the documentation

**Comment by cderv** [comment]
> We could probably add it to the documentation

I added to the doc.
