### ISSUE TITLE
Preview toolbar button in VS Code looks weird

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto#387]
Since the latest VS Code update (1.87.0), the Preview button in the toolbar (top right by default) spans two lines and includes its keyboard shortcut:

![Screenshot 2024-02-29 at 08 29 04](https://github.com/quarto-dev/quarto/assets/4377312/f563250c-f633-496e-92bf-56002d67e987)

This is on the latest version of the Quarto extension v1.110.1.

**Comment by mcanouil** [comment]
The tooltip is indeed added as text in the button.
I am not entirely sure that's on the extension though.

**Comment by jjallaire** [comment]
Fixed here (https://github.com/quarto-dev/quarto/commit/55b895015ba207e95f9a332304989e3520ea91b6) and published as version 1.111.0

**Comment by mcanouil** [comment]
For reference mostly, the screenshot of the new behaviour/UI:
<img width="143" alt="image" src="https://github.com/quarto-dev/quarto/assets/8896044/5ae142a0-f2fa-4740-b230-506fdd388503">
