### ISSUE TITLE
Add option to disable/hide Quarto panel

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto#39]
I don't really need the Quarto panel, which always appears in the lower panel (even when no Quarto document is open). It would be great if (1) the panel is shown only when Quarto files are open and/or (2) there was an option to disable/hide the panel completely.

**Comment by jjallaire** [comment]
This should be resolved here: https://github.com/quarto-dev/quarto/commit/29e983f86eff82b7e1211b0cbcd4cc5b39356b4d
