### ISSUE TITLE
Ctrl+Enter executes R and Python code but not bash

### ISSUE THREAD

**Issue by Robinlovelace** [quarto-dev/quarto#4]
As shown below: 

![image](https://user-images.githubusercontent.com/1825120/204927556-1e1a79a8-57ff-489b-82de-ad4cade6a34d.png)

Any way to get it to execute bash commands?

**Comment by jjallaire** [comment]
We've just added support for "Run Cell" for bash: https://github.com/quarto-dev/quarto/commit/250a98441c403c25630f61a1234290273ff2877d

**Comment by Robinlovelace** [comment]
Awesome. Thanks! Shall I give it a test run?

**Comment by jjallaire** [comment]
Yes, we just pushed an update to the marketplace w/ this (v1.63.0)

**Comment by Robinlovelace** [comment]
![Peek 2023-02-10 00-05](https://user-images.githubusercontent.com/1825120/217967188-6fe84d00-d402-4c50-88bf-76bccfec6e98.gif)

Confirmed. Demo above. Many thanks!

**Comment by gortegasolis** [comment]
Hi, 
Bash is not working for me. I tried adding "engine: knitr" and adding first an R chunk but nothing works.

This is my system:

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-35-generic

**Comment by mdehollander** [comment]
Same here, doesn't seem to work (anymore)

**Comment by Robinlovelace** [comment]
Worth testing and reopenning @jjallaire and team?

**Comment by sharon-wang** [comment]
For those following along, new issue opened here: https://github.com/quarto-dev/quarto/issues/687
