### ISSUE TITLE
Multi-line Julia Code

### ISSUE THREAD

**Issue by BradyAJohnston** [quarto-dev/quarto#40]
When working in VSCode, multi-line code runs if you run the whole cell, but if the code is split over multiple lines and you use the CMD + Enter / Ctrl + Enter to run a single-line, it only attempts to run the one line and breaks. 

With the chunk below, hitting Ctrl+Enter on the first line:

```julia
randn(
    10
)
```

Results in this error: 
```bash
julia> randn(
ERROR: syntax: incomplete: premature end of input
Stacktrace:
 [1] top-level scope
   @ code:1
```

Multi-line but not whole-chunk execution would be very handy. Thanks for the great plugin so far though!

**Comment by jjallaire** [comment]
This should work now for R.

For Python and Julia, we need the native extensions to provide a command or API that implements this. Julia appears to have one in the `language-julia.executeCodeBlockOrSelectionAndMove` command, but it doesn't seem to work for qmd files.

**Comment by andycraig** [comment]
For Python there is a new extension that provides some functionality along these lines: https://github.com/kylebarron/vscode-jupyter-python/blob/1f3a196dffd8ecd746dada7cbdc71be9716aded3/src/run-code.ts#L41

**Comment by jjallaire** [comment]
From looking at the source code it appears as if this _should_ work with qmd files w/o any special configuration. Have you found that to be the case? This also might be something we could incorporate directly into the quarto extension (as things stand now the keyboard shortcuts conflict by default so it might be more straightforward if we defined/implement this internally in a similar fashion).
