### ISSUE TITLE
Auto formatting code blocks?

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto#41]
Thank you so much for working on this extension.
I was impressed to see how quickly you implemented the auto-completion of options and the ability to run code blocks.

One thing I think is missing is the ability to auto-format code blocks.
I don't know if the auto-formatting feature is feasible since this extension appears to make LSP work by copying the code in the code block to another script file, but it would be great if it could be done. (As far as R is concerned, we can auto-format by temporarily changing the file type to RMarkdown.)

**Comment by tomshafer** [comment]
+1 for this. Many thanks!

**Comment by jjallaire** [comment]
This is now implemented in v1.66.0. Format Document and Format Selection/Cell are both available, keyed off of the cell where the cursor is located (or failing that using the language most frequently appearing within executable cells in the document).

This currently works for Python and Julia. It is enabled for R but there are some things we need to work through w/ the VS Code R extension to make it work properly.
