### ISSUE TITLE
With VS Code extension, "Quarto: Insert Code Cell" requires user to choose language for each new chunk

### ISSUE THREAD

**Issue by juliasilge** [quarto-dev/quarto#425]
When using the VS Code extension, you can use "Quarto: Insert Code Cell" (such as via its keyboard shortcut) to make a new code cell/chunk. However, it requires the user to choose the language every time:

https://github.com/quarto-dev/quarto/assets/12505835/955130ea-37ff-41e2-9734-bcc9eb23fc29

We are hearing from users that they would prefer the RStudio behavior where making a new code chunk uses the language from the previous code chunk. It is fine to have users choose for the first chunk, but it doesn't feel great to have to keep choosing the language over and over.

**Comment by mcanouil** [comment]
FYI:

- https://github.com/quarto-dev/quarto/issues/405

**Comment by mikemahoney218** [comment]
A bit of a delayed response but FWIW, I think this is meaningfully distinct from #405. Ideally this would mean the language of each file is detected, irrespective of user profile settings, and automatically populated for all but the first cell.

**Comment by jennybc** [comment]
I'm bumping into this very hard right now, working on many existing `.Rmd` vignettes in a package. I did upvote above, but that didn't seem like a strong enough endorsement for this issue 😅 It would be really awesome to _not_ have to replace `python` with `r` repeatedly.

**Comment by DavisVaughan** [comment]
See https://github.com/quarto-dev/quarto/issues/539 for the direct comparison with RStudio, strongly agree we should tweak this

**Comment by DavisVaughan** [comment]
Looks super easy, let me give it a shot https://github.com/quarto-dev/quarto/blob/f15c1f91a59db9ffb22990da3bdef2ddb49f7bdd/apps/vscode/src/providers/insert.ts#L101-L117

**Comment by mcanouil** [comment]
@gujunhk thanks but what you are suggesting is not even valid.
Also, the issue was closed by a PR that addresses the issue.
