### ISSUE TITLE
Quarto Jupyter kernel ZMQ Error

### ISSUE THREAD

**Issue by heath-r** [quarto-dev/quarto#427]
Original post removed as requested by customer. Please close this issue. They will post there own message.

**Comment by cscheid** [comment]
@heath-r Unfortunately, quarto doesn't do anything special with respect to the jupyter setup (we simply use whatever version of jupyter that is available in the PATH). So if the customer is getting a ZMQ error inside jupyter, that points to some problem or another in their environment.

**Comment by heath-r** [comment]
Original post removed as requested by customer. Please close this issue. They will post there own message.
