### ISSUE TITLE
cell error when trying to run multiple cell at once (run above/below) in the interactive's python sessione for qmd files (it's fine when rendering with quarto) 

### ISSUE THREAD

**Issue by kompre** [quarto-dev/quarto#43]
Hello,

When I get back to a qmd files with a bunch of python cell in a qmd files and I try to run all cell at once I get a bunch of errors, mostly due to the interactive session not being able to find variables in the namespace. It seems like at some point a cell tries to run before the previous one are returned, therefore not being able to find variables defined above. It will run correctly if each celle is run one by one.

This issue is present only for the interactive session. When I properly render the document with quarto, ti will render correctly.

I've converted the qmd file to ipynb to see if it was an issue with vscode itself not being able to keepup with the cell, but it will run smoothly as an ipynb file.

I think the issue is with the execution time of the cell: some take quite few seconds to return if they are doing intensive task like `from sympy import *` or working with *largish* pandas dataframe.

**Comment by kenf1** [comment]
Same issue but with `quarto.runAllCells`, `quarto.runCellsAbove`, and `quarto.runCellsBelow` keyboard shortcuts.

---

This runs in order: (chunk 1 -> 3)

![1](https://user-images.githubusercontent.com/103538771/213461344-9edbc3ac-835d-458c-9962-78a90860d2b7.png)

---

This runs in reverse: (chunk 3 -> 1)

![2](https://user-images.githubusercontent.com/103538771/213450895-c6f6f9f5-1f4a-4016-b797-c17060ce4180.png)

---

Using `Run Above` runs code chunks in 1 -> 3 in both instances.

VSCode: 1.74.3
Quarto: 1.2.280

**Comment by jjallaire** [comment]
Resolved this here: https://github.com/quarto-dev/quarto/commit/09d495db64df5b27d9b8d80ecafd26997ac163e4

It looks like the Python extension does not wait on the code to complete execution before returning from the `jupyter.execSelectionInteractiveCommand`. This means the we need to concatenate all of the cells together and run them in one shot. That's how we originally implemented the feature but we got feedback that running cell by cell would be nicer. While I agree with this, I don't think its sustainable if it results in out of order execution.

This should be available in the next release (by early next week).

**Comment by jjallaire** [comment]
Unfortunately this change broke the use of cell magics (reported here: https://github.com/quarto-dev/quarto/issues/83) so we are going to have to revert. If there is a clean mechanism or API for us to ensure the cells are run in order I would love to know about it and use it, but I don't see one at this point. I'll reopen this to track finding a way forward.

**Comment by johnros** [comment]
Having the same problem. 

I also suspect it is the same issue reported [here](https://community.rstudio.com/t/running-python-cells-in-a-quarto-file-with-interactive-vscode/167097).

**Comment by patgd** [comment]
Chiming in to report I have the same issue.

Has anyone found a workaround? It's strange that it's affecting some users and not others.

I'd take broken IPython magic over out-of-order cell execution.

Is the current solution to use an editor other than VSCode?

**Comment by grst** [comment]
I have another repex:

Choosing `Quarto: Run all cells` on
````qmd
```{python}
print(1)
from time import sleep

sleep(10)
```

```{python}
print(2)
```

```{python}
print(3)
```
````

results in 

![image](https://github.com/quarto-dev/quarto/assets/7051479/a330ed86-6a5b-4fcf-9b46-e78d347801c1)


There must be a way to do this via the vscode API, because the same as "percent script" with `Jupyter: Run all cells`
````python
# %% 
print(1)
from time import sleep
sleep(10)

# %%
print(2)

# %%
print(3)
````

works fine: 

![image](https://github.com/quarto-dev/quarto/assets/7051479/1a9336b7-a72a-4627-8325-963658bb26d8)

**Comment by jjallaire** [comment]
@grst I so wish that gave us a path to get this working right! Unfortunately the API used to run percent cells is fully internal to the Jupyter extension (so not accessible to 3rd party extensions).

I think the right solution here is to conditionalize the execution behavior such that we run all the python cells together if there are no magics (and use the current behavior when we do see magics). Will try to make that change soon!

**Comment by jjallaire** [comment]
Made this change here: https://github.com/quarto-dev/quarto/commit/ea2c68b15794a4829f4dc8f94e9f4b196d599d30
