### ISSUE TITLE
VScode preview not available?

### ISSUE THREAD

**Issue by DarvidTorres** [quarto-dev/quarto#45]
I was able to render the Hello, Quarto tutorial, and I find the rendering in my working directory (I even can open it) but I don't see any preview in VSCode? The extension settings are set as default internal preview and reveal the panel preview but I don't see any panel and don't know how to open it. 

Here's my terminal:

PS C:\Programming\R\R Programming A-Z> quarto preview "c:/Programming/R/R Programming A-Z/hello.qmd" --no-browser --no-watch-inputs

Starting python3 kernel...Done

Executing 'hello.ipynb'
  Cell 1/1...Done

pandoc 
  to: html
  output-file: hello.html     
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Basics
  jupyter: python3

Output created: hello.html

Watching files for changes

**Comment by jjallaire** [comment]
This is surprising as we haven't had other reports of preview not showing up! If you go to the **Output** tab in the panel and then select **Extension Host** do you see any debug messages from the Quarto extension?

**Comment by DarvidTorres** [comment]
I don't know what was wrong with my install (and I never will). I had to remove VSCode and all its components from my machine, reinstall and so it worked.

**Comment by jjallaire** [comment]
Okay, thanks for the follow up and glad things are working now!
