### ISSUE TITLE
Quarto VSCode: Request textDocument/completion failed

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto#46]
After installing the prerelease version of quarto CLI, I see the following error:

I just tried to insert a new citation.

![image](https://user-images.githubusercontent.com/19754711/210124423-2350bec4-c809-4e9a-80db-1d78fdcd3c5f.png)

It seems like a required lua file was missing or the path has changed?

**Comment by jjallaire** [comment]
This should be resolved with recent updates to the CLI and extension. Let us know if you continue to see the issue.
