### ISSUE TITLE
Feature request: add a dropdown button to select language for a code snippet

### ISSUE THREAD

**Issue by mdehollander** [quarto-dev/quarto#461]
With R Markdown notebooks you can select the language when inserting a code chunk. With Quartro notebooks this is not present, where manually changing r to bash after a code chunk has been inserted works. A dropdown would be more user friendly.

| notebook | image| 
|----|----|
|Quartro |![image](https://github.com/quarto-dev/quarto/assets/262872/fa4a3163-380c-4bc6-8432-251a7a5391ab) |
|R Markdown | ![image](https://github.com/quarto-dev/quarto/assets/262872/22a69193-e479-444d-a6cb-df750ff6ffd4)|

**Comment by cscheid** [comment]
(I think these screenshots come from RStudio, right?)

**Comment by mdehollander** [comment]
Yes, indeed, it's from RStudio. Now I realize you can use Quartro also in other ways like vscode 🙂
________________________________

**Comment by cscheid** [comment]
In that case, you're looking for this repository instead: https://github.com/rstudio/rstudio/
