### ISSUE TITLE
Save button triggers rendering ipyn notebook after having rendered it

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto#49]
This may be related to a previous bug that I reported:

https://github.com/quarto-dev/quarto/issues/3

Steps to reproduce it:

1. Open a `ipyn` notebook.

2. Render it with `CONTROL+SHIFT+K`.

3. Close the PDF output window.

4. Whenever one clicks on the save button, the `ipyn` notebook is rendered.

**Comment by psads-git** [comment]
I forgot to mention that this issue occurs in VSCode.

**Comment by jjallaire** [comment]
This issue should be resolved with this fix: https://github.com/quarto-dev/quarto/commit/cfc02b959349a474a36b6261b29291457e7a366c
