### ISSUE TITLE
Misplaced accents in revealjs format

### ISSUE THREAD

**Issue by dar143** [quarto-dev/quarto#499]
The hat accent is placed to the right of the character for revealjs
format: html works fine

```
---
title: "Beta_hat_issue"
author: "RD"
format: revealjs
---

## Putting the hat on top of the Greek character

$$
y = \hat\beta X
$$

```

**Comment by dar143** [comment]
This is running 
Quarto 1.5.54
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.54
      Path: /Applications/quarto/bin

**Comment by cderv** [comment]
See 
- https://github.com/quarto-dev/quarto-cli/issues/6263

BTW for Quarto CLI problem. Please search and if necessary open an issue in the other repo. This one if for VSCODE extension, and other tooling for Quarto.
