### ISSUE TITLE
Red text highlighting in VSCode extension when more than one line in the title block

### ISSUE THREAD

**Issue by dbdean** [quarto-dev/quarto#501]
I'm running the Quarto VSCode Extension version 1.113.0, inside of a dev container. I seem to have the same problem when downgrading to 1.112.0, so I don't think the following problem is directly related to a change in the extensions itself.

I'm not sure what has changed recently to cause this, but whenever I open a qmd file with more than one line in my title block, the quarto extension is causing all python code to show up as red text.

For example, this is fine:

![image](https://github.com/user-attachments/assets/9055f866-4247-478f-be5d-65eaf9b8f5ca)

As is this:

![image](https://github.com/user-attachments/assets/726487ba-0f1a-41cb-812e-b463b7636bc5)

But if I add another line to the title block, I get red python text:

![image](https://github.com/user-attachments/assets/99e786d3-c937-4f4a-a08d-10e797f5da09)

Even just an extra blank line will do it:

![image](https://github.com/user-attachments/assets/9c859c16-060a-40bf-b24b-c1b77b4c9d5a)

This has only just started happening for me, and VSCode's extension bisect has confirmed that it is being caused by the Quarto Extension.

Any ideas on what could be happening and how to fix it would be very appreciated. It appears to have no impact on the functionality otherwise, but it is a lot harder to follow the code when everything is red.

**Comment by dbdean** [comment]
Looking at the token inspector, it seems to think it should be yaml there, and is doesn't like it as yaml:

![image](https://github.com/user-attachments/assets/4cd5a0ef-73e1-4121-9c65-ee363b249ebb)

Whereas with just the single-line title block, it recognises it as python:

![image](https://github.com/user-attachments/assets/03ec5dcd-b72c-46e4-82ef-2fb5496dc981)

**Comment by benesom** [comment]
I can report the same behavior on MacOs 14.5 (23F79) with VScode 1.92.0.

**Comment by alptemiz** [comment]
Same here, using Windows with VS Code 1.92.0, Quarto 1.5.56, and R 4.4.1. 

If you remove the YAML codes at the top, you'll notice that your code appears with normal syntax highlighting. However, this workaround will prevent your code from rendering properly.

A temporary solution is to **downgrade** to VS Code 1.91.1, where everything works fine. 

The Quarto team will likely resolve this issue in the next version. Until then, don't forget to **disable auto-updates** in VS Code to avoid any disruption.

**Comment by memeplex** [comment]
Indeed, this fails in the simplest of the examples:

<img width="483" alt="image" src="https://github.com/user-attachments/assets/eec164ec-b7d9-43b7-abe3-7c02192867b6">

It's not immediately visible at that level, but the grammar is already wrong.

Inside second level sections the problem surfaces:

<img width="216" alt="image" src="https://github.com/user-attachments/assets/1268df6a-864f-4d22-b7d4-cff2077908b2">

**Comment by memeplex** [comment]
https://github.com/microsoft/vscode/issues/220026

**Comment by memeplex** [comment]
Also, notice that I'm using pandoc syntax, but it's exactly the same when both delimiters are `---`.

**Comment by SaintRod** [comment]
Experiencing the same behavior on Linux Mint 21.3 with VS Code v1.92.0 Quarto v1.5.54

**Comment by memeplex** [comment]
According to https://github.com/microsoft/vscode/issues/224627#issuecomment-2266084539 it's not a regression in VSCode but that the qmd grammar should be updated according to the new grammar in VSCode.

**Comment by RedCMD** [comment]
FrontMatter integration should be updated to match Markdowns

https://github.com/quarto-dev/quarto/blob/06678d55143a7d6de6c7f0232db0c5dcf8392ca6/apps/vscode/syntaxes/quarto.tmLanguage.yaml#L226-L231

https://github.com/microsoft/vscode-markdown-tm-grammar/pull/162

https://github.com/microsoft/vscode-markdown-tm-grammar/blob/main/markdown.tmLanguage.base.yaml#L202-L216

**Comment by mcanouil** [comment]
Weirdly, it does not seem to happen on macOS, but it does on UNIX and Windows system.

https://github.com/user-attachments/assets/f75f0d91-df5b-4fdd-b252-9af0a1f1eb61

**Comment by mcanouil** [comment]
@RedCMD From what I understand, a simple PR to update the definition would be enough, correct?

**Comment by mcanouil** [comment]
Ok, I've made a PR and reached out to the repository owners.

- https://github.com/quarto-dev/quarto/pull/506

**Comment by memeplex** [comment]
> Weirdly, it does not seem to happen on macOS

It does happen on macOS Sonoma for me.

**Comment by mcanouil** [comment]
Thanks.

The fix is being tested to ensure it does not break other things that use the extension.
