### ISSUE TITLE
Hide green dot in pdf viewer

### ISSUE THREAD

**Issue by memeplex** [quarto-dev/quarto#502]
There is a distracting green dot announcing an outline that reappears after every refresh when there is a section in the document:

<img width="214" alt="image" src="https://github.com/user-attachments/assets/1cca8057-1dac-4828-ad58-5826536a9a5e">

I've worked on a pdfjs preview extension myself in the past and IIRC I disabled that annoying little dot with this:

```html
<style>
    .pdfSidebarNotification::after { display: none; }
</style>
```

**Comment by cscheid** [comment]
That's good that you fixed it for your preference, but that dot exists for a reason.

**Comment by memeplex** [comment]
But the reason is informing that there is an one outline there, do you really think that's useful when you're not opening a random document for the first time but just refreshing your wip every other second?
