### ISSUE TITLE
Quarto cannot find module mlxtend

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto#51]
Consider the following `qmd` document:

````
---
title: "Untitled"
format: pdf
jupyter: r-reticulate
---

```{python}
import mlxtend
```
````

When rendering this document, both in VS Code and in RStudio, I get the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 1
----> 1 import mlxtend

ModuleNotFoundError: No module named 'mlxtend'
ModuleNotFoundError: No module named 'mlxtend'

```

The module `mlxtend` is installed, and can be loaded, without any issue, when importing it in a normal `ipnb` notebook.

**Comment by cderv** [comment]
> `jupyter: r-reticulate`

Is `r-reticulate` a Jupyter Kernel you have defined ? 
`jupyter` field in YAML is for that: https://quarto.org/docs/computations/python.html#kernel-selection

Can  you share more information about the setup you have regarding Python ? 

Can you share `quarto check jupyter` results ? 

Thank you

**Comment by psads-git** [comment]
Thanks, Christophe, for your reply.

The workaround I have found to overcome this problem was to install 

`mlxtend`

on the python environment I have on my home directory.

Here, it is what you asked for:

```
$ quarto check jupyter

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /usr/bin/python3
      Jupyter: 5.1.3
      Kernels: r-reticulate, python3, ir

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

$

```

**Comment by cderv** [comment]
Nice that you made it worked. 

> on the python environment I have on my home directory.

Which environment where you initially targeting to use ?  From Quarto checks results it seems that `/usr/bin/python3` is the Python version used, and the environment that goes with it

**Comment by psads-git** [comment]
Thanks again, Christophe.

I was targeting:

`~/.virtualenvs/r-reticulate/bin/python3`

The reported problem occurred only in the context of `quarto`: When using a `.ipyn` document, everything went fine.

**Comment by cderv** [comment]
Here is our current write up on virtual environment: https://quarto.org/docs/projects/virtual-environments.html

When using theses tools, you need to set up your IDE or Terminal to activate the desired environment, so that when running Quarto the correct environment is used. I am not sure it is in your example. Can you check that ? 

Activating an environment should make the `python3` found in PATH the one from the environment, and so Quarto should use it. As I said Quarto will use the Python found in PATH.

**Comment by psads-git** [comment]
Thanks again, Christophe.

I ran 

`python3 -m venv /home/x/.virtualenvs/r-reticulate/`

but when rendering the `quarto` document, got again the mentioned error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import mlxtend

ModuleNotFoundError: No module named 'mlxtend'
ModuleNotFoundError: No module named 'mlxtend'

```

If I open a normal `.ipyn` notebook, 

`import mlxtend`

gives no error at all, even when the `r-reticulate` virtualenv is selected.

**Comment by cderv** [comment]
> I ran `python3 -m venv /home/x/.virtualenvs/r-reticulate/`

This is to create the `venv`. In the terminal, or the IDE you are using, need to activate it. Check `which python` or `quarto check jupyter` to see which `python3` binary is used.

**Comment by psads-git** [comment]
The problem persists, Christophe, even after having activated the virtualenv:

```
$ quarto check jupyter

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /home/x/.virtualenvs/r-reticulate/bin/python3
      Jupyter: 5.1.3
      Kernels: python3, r-reticulate, ir

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK
$

```

**Comment by psads-git** [comment]
I have just checked: The problem also occurs in RStudio.

**Comment by cderv** [comment]
> [✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /home/x/.virtualenvs/r-reticulate/bin/python3
      
so here that is good - it means the correct virtual env is found.

> even after having activated the virtualenv:

`mlxtend` is correctly installed inside this virtualenv `/home/x/.virtualenvs/r-reticulate` right ?  

> It seems that frozen modules are being used

I don't know what that means and if it could create some issues. Maybe you could try 

* A fresh virtual environment
* Install required package for Quarto following docs
* Install `mlxextend`
* Testing if Quarto still have issues. 


Thank you for helping me debug

**Comment by psads-git** [comment]
The command 

` import mlxtend`

works fine outside `quarto`:

```
(r-reticulate) [x@localhost ~]$ python
Python 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlxtend
>>> 
>>> 
```

I am now going to use a freshly created virtualenv.

**Comment by cderv** [comment]
> works fine outside quarto:

Ok so that is for some reason not found 🤔 

> I am now going to use a freshly created virtualenv.

That will be helpful as then you 
* share the command you've done 
* I could try exactly the same on my side and see if I get the same.

**Comment by psads-git** [comment]
I think I have found out what is causing the issue: It is the following line in the `YAML` section: 

`jupyter: r-reticulate`

If one removes that line, everything works fine, Christophe!

**Comment by cderv** [comment]
Good to know. As I said in my first message https://github.com/quarto-dev/quarto/issues/51#issuecomment-1385590626 

> Is r-reticulate a Jupyter Kernel you have defined ?
> jupyter field in YAML is for that: [quarto.org/docs/computations/python.html#kernel-selection](https://quarto.org/docs/computations/python.html#kernel-selection)

Glad to know it works for you. I'll close this then - thank you !

**Comment by psads-git** [comment]
I would suggest if I may, Christophe, to have `quarto` returning a more informative error message, to direct users to what the problem is. 

Moreover, 

`r-reticulate`

should not be allowed to be considered, by `quarto`, as a _valid_ `jupyter` kernel -- it should have the word `python` (or maybe `R`, assuming `jupyter` also works with `R`).

**Comment by cderv** [comment]
I'll look into that. 

> $ quarto check jupyter
>
> [✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /usr/bin/python3
      Jupyter: 5.1.3
      Kernels: r-reticulate, python3, ir

But as seen above, `r-reticulate` is seen as a kernel by Quarto - Not sure why exactly. I'll try to reproduce this
