### ISSUE TITLE
Improve website search

### ISSUE THREAD

**Issue by cgraham-rs** [quarto-dev/quarto#514]
Website search currently fails to find results where the text includes special characters such as punctuation unless you explicitly include the punctuation in the query.

This was discovered while searching Connect documentation for `off host` and not finding the expected results as the content is specifically `off-host`

To reproduce, using this quarto website `index.qmd`
```
---
title: "quarto-website"
---

This is a Quarto website.

Try to search for `find me` and see what results appear when the website includes the hyphenated word find-me.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
```

- Open a preview
- Click the Search icon
- Enter `find` or `me` or `find me` in the search query input
- Observe "find me" is a match
- Observe "find-me" is not
- You must explicitly search for `find-me` to locate that specific result in the document/website
- Searching for `find*` or `find*me` with a wildcard generates zero results

<img width="763" alt="image" src="https://github.com/user-attachments/assets/9ac6432d-a24a-4939-87c7-af61792b1df4">

<img width="763" alt="image" src="https://github.com/user-attachments/assets/0b1c9ffa-ec65-4c50-8d0b-56ea3bfe109e">

<img width="763" alt="image" src="https://github.com/user-attachments/assets/fd415562-b248-4c64-b344-4ba6335dbce8">

**Comment by cscheid** [comment]
Unfortunately this is something we don't control and can't fix, given that we use a third-party engine for the search.
