### ISSUE TITLE
Why is not Quarto able to render documents with ipython magic?

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto#53]
Consider the following document:

````
---
title: "Untitled"
format: pdf
jupyter: r-reticulate
---

```{python}
%load_ext rpy2.ipython
```
````
when rendered, it produces the following error:

```
An error occurred while executing the following cell:
------------------
%load_ext rpy2.ipython
------------------

```
So my question is: Should not Quarto be able to render documents with `ipython` magic?

**Comment by psads-git** [comment]
With the help of @shafee (see: https://stackoverflow.com/questions/75024926/is-quarto-able-to-render-documents-with-ipython-magic/75025012#75025012), to whom I very much thank, it was found out that `quarto` can render `ipython` magic. Although `rpy2` was installed in `r-reticulate` environment, the problem occurred. However, after having installed `rpy2` in the default `python` environment, the issue vanished, even when using `r-reticulate` environment.

**Comment by cderv** [comment]
Can you share more about the `r-reticulate` environment, and also about the steps we need to take to reproduce the issue with some environments as close as you have ? 

Thank you

**Comment by psads-git** [comment]
Thanks, Christophe, for your reply.

The steps to reproduce the issue:

1. Create a Python virtualenv in a directory different from the home one.

2. In this newly created virtualenv install `rpy2`.

3. Create another Python virtualenv in the home directory.

4. Create a quarto document that uses the first created virtualenv and that uses `rpy2` through magic.

**Comment by jjallaire** [comment]
@cderv I think the issue here just boils down to rpy2 not being available in the environment they were rendering in (the confusion was b/c it was already available in `r-reticulate`). So I don't think there is an issue to be addressed here now that they have figured out the source of the problem (feel free to re-open if there is an issue).
