### ISSUE TITLE
Provide support and compatibility with Zed

### ISSUE THREAD

**Issue by datacubeR** [quarto-dev/quarto#530]
Hi guys,
Quarto is awesome and Zed is becoming the new kid on the block and a strong competitor for VSCode, will you provide support for Quarto on Zed? It cpould be a really easy win.

Thanks in advance,

Alfonso

**Comment by cderv** [comment]
Seems like something more targeted to Zed directly. 

For reference, related feature request
- https://github.com/zed-industries/zed/issues/12406

**Comment by cscheid** [comment]
Not something to be fixed here.
