### ISSUE TITLE
non-standard quarto location?

### ISSUE THREAD

**Issue by kkmann** [quarto-dev/quarto#55]
Hi,

Quarto (+VSC) looking pretty awesome already - thanks :)

I have my quarto installation in `$HOME/quarto/${VERSION}` and use `.bashrc` to modify the PATH manually. This leads to 
```
/bin/sh: quarto: command not found
```

It would be great to be able to use the extension in an environment where quarto is installed in a non-standard location (e.g. user home) or document the lookup path. Maybe just make the path to the quarto binary a config entry?

**Comment by kenf1** [comment]
Are you using macOS? If so, the quarto VS Code extension should be able to detect where quarto is installed without you specifying the path.

As for adding path to quarto binary, the option is already present in VS Code settings under `Quarto: Path`.

**Comment by kkmann** [comment]
red hat 7 via remote ssh extension. I don't see that option in the settings menu of the extension. Do I need to set that directly in settings.json? Is
```
"quarto.path": "[path to quarto]"
```
correct?

**Comment by jjallaire** [comment]
Yes that is indeed correct!
