### ISSUE TITLE
Shinylive R not rendering

### ISSUE THREAD

**Issue by kv9898** [quarto-dev/quarto#557]
Also reported in https://github.com/posit-dev/positron/issues/4844

## System details:

Windows 11 64-bit

#### Version details:

Positron Version: 2024.09.0 (system setup) build 77
Code - OSS Version: 1.93.0
Date: 2024-09-23T02:44:07.418Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Quarto: 1.6.15
shinylive (R package): 0.2.0
#### Interpreter details:

R 4.4.1

## Describe the issue:

Maybe related to https://github.com/posit-dev/positron/issues/4676. Seems to be a *Windows only* issue. I can confirm that this *is a Positron or VS Code/Quarto VS Code extension problem* as my RStudio runs normally, in line with the previous issue but different from @jennybc's results. I will try to provide more information than my predecessor. Please let me know if there is more info needed.

In a nutshell:

- Positron/VS Code + Quarto + Shinylive + R = ×
- Positron/VS Code + Quarto + Shinylive + Python = √
- RStudio + Quarto + Shinylive + R = √

## Steps to reproduce the issue:

1. Start a new folder for the Quarto project
2. Open the folder in Positron/VS Code
3. Execute `quarto add quarto-ext/shinylive` in Terminal to install the Quarto extension.
4. Run `install.packages("shinylive")` if it has not been installed before.
5. Start a .qmd file
6. Include the following minimum quarto document, and render:

````qmd
---
title: "Shinylive R test"
filters:
  - shinylive
---
```{shinylive-r}
#| standalone: true

```
````
7. You get an error.

## Expected or desired behavior:

Running normally as in RStudio.
![image](https://github.com/user-attachments/assets/c528598e-96d6-4c59-b161-980ce5991ba3)

From RStudio Background Jobs:
```
==> quarto preview shinyliver.qmd --to default --no-watch-inputs --no-browse

pandoc 
  to: html
  output-file: shinyliver.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Shinylive R test
  
ℹ Loading metadata database
✔ Loading metadata database ... done

Output created: shinyliver.html

Watching files for changes
Browse at http://localhost:5239/
```

## Were there any error messages in the UI, Output panel, or Developer Tools console?

From Positron/VS Code Terminal:
```
PS D:\OneDrive - London School of Economics\Desktop\shinyliveRError> quarto preview "d:/OneDrive - London School of Economics/Desktop/shinyliveRError/shinyliver.qmd" --no-browser --no-watch-inputs
pandoc 
  to: html
  output-file: shinyliver.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Shinylive R test

(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
 Error:
 PandocError {}
Error running filter D:/quarto/share/filters/main.lua:
...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:40: Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?

stack traceback:
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:40: in global 'throw_quarto_error'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:86: in global 'callRShinylive'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:113: in global 'callShinylive'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:286: in global 'ensureBaseSetup'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:315: in global 'ensureLanguageSetup'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:424: in function <...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:408>        
        [C]: in ?
        [C]: in method 'walk'
        D:/quarto/share/filters/main.lua:558: in local 'checked_walk'
        D:/quarto/share/filters/main.lua:610: in function 'run_emulated_filter'
        D:/quarto/share/filters/main.lua:1335: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        D:/quarto/share/filters/main.lua:1351: in upvalue 'run_emulated_filter_chain'
        D:/quarto/share/filters/main.lua:1389: in function <D:/quarto/share/filters/main.lua:1386>
stack traceback:
        D:/quarto/share/filters/main.lua:558: in local 'checked_walk'
        D:/quarto/share/filters/main.lua:610: in function 'run_emulated_filter'
        D:/quarto/share/filters/main.lua:1335: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        D:/quarto/share/filters/main.lua:1351: in upvalue 'run_emulated_filter_chain'
        D:/quarto/share/filters/main.lua:1389: in function <D:/quarto/share/filters/main.lua:1386>
  ```

**Comment by davidrsch** [comment]
Hello @timtmok I forgot to update status about this in the issue I opened at Positron IDE I do not longer have this issue. 

## System Details

Windows 10 64-bit (OS Build 19045, 4894)

#### Version details

Positron Version: 2024.09.0 (system setup) build 77
Code - OSS Version: 1.93.0
Commit: 9b6f7c066546a4c7f104368fc769fb3768b08bfd
Date: 2024-09-23T02:44:07.418Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045 

Quarto 1.5.56
shiinyle 0.2.0

Interpreter details:
R 4.4.1

I don't recall doing anything special to fix this issue. I decided to try it again other day and worked. Maybe it's related to the quarto version.

**Comment by cscheid** [comment]
```
(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
```

Can you file this at shinylive? https://github.com/posit-dev/r-shinylive

**Comment by kv9898** [comment]
> ```
> (E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
> ```
> 
> It doesn't look like Quarto is doing anything special here, and Shinylive is somehow failing to file `Rscript`. Can you file this at shinylive? https://github.com/posit-dev/r-shinylive

Yes, just did it (https://github.com/posit-dev/r-shinylive/issues/133).

**Comment by kv9898** [comment]
Update: The problem is solved after adding R to PATH. The error of "Perhaps you need to install / update the 'shinylive' R package" was somehow misleading... I was surprised that RStudio/Positron/Quarto worked so long without any errors without R in PATH.

**Comment by cscheid** [comment]
> Update: The problem is solved after adding R to PATH. The error of "Perhaps you need to install / update the 'shinylive' R package" was somehow misleading... I was surprised that RStudio/Positron/Quarto worked so long without any errors without R in PATH.

```
(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
 Error:
 PandocError {}
Error running filter D:/quarto/share/filters/main.lua:
...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:40: Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
```

Notice where the error came from: `_extensions\quarto-ext\shinylive\shinylive.lua`. That's not Quarto; that's the shinylive extension itself. I'm going to go ahead and close the issue.

**Comment by jennybc** [comment]
> I was surprised that RStudio/Positron/Quarto worked so long without any errors without R in PATH

I can speak to the Positron + Windows part of this. By default, the CRAN R installer for Windows does not put R on the PATH. Therefore R installation discovery focuses on well-known places and learning from the registry instead. Most Windows users will not have R on the PATH, so a naked call to `R` or `Rscript` is going to fail.

**Comment by cscheid** [comment]
> Most Windows users will not have R on the PATH, so a naked call to `R` or `Rscript` is going to fail.

This is something we probably should let @schloerke know at https://github.com/posit-dev/r-shinylive, given

https://github.com/quarto-ext/shinylive/blob/d93c9f217fd23d44deaabe3ed51b3ba4dc61ba14/_extensions/quarto-ext/shinylive/shinylive.lua#L81

**Comment by kv9898** [comment]
That seems clear now. I though I accidentally unchecked the "add to PATH" box when I installed R. I have passed on your messages at https://github.com/posit-dev/r-shinylive/issues/133#issuecomment-2389117135

**Comment by cscheid** [comment]
@kv9898 wrong repository: you commented on `posit-dev/r-shinylive`, but the issue needs to be addressed on `quarto-ext/shinylive`.
