### ISSUE TITLE
Update Mermaid from 9.4.3 to 11.3.0

### ISSUE THREAD

**Issue by mmyrte** [quarto-dev/quarto#570]
Repeating issue #67 since I don't know how to handle this differently - mermaid-js has released two major versions since the last upgrade. I quite fancy some of the newer refinements, e.g. having an `until` keyword in Gantt-Charts.

I don't want to create a PR myself to vendor in the new version, since I know too little about quarto's dependency management.

<https://github.com/mermaid-js/mermaid/releases/tag/mermaid%4011.3.0>

**Comment by cderv** [comment]
Quarto 1.6 current pre-release has update to mermaid 11.2 - you can get it and see release note at  https://quarto.org/docs/download/

BTW repo for the Quarto CLI is https://github.com/quarto-dev/quarto-cli/ 

You should follow such work and search there next time. 

Thanks for the feedback.
