### ISSUE TITLE
Implement/Enable "Go To Definition" in VS Code

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto#60]
Currently, hovering over an object name shows a tooltip with the line where the object is defined, but the proper "Go To Definition" (via F12) or the other "Definition-related" (Peek, open to the side) are not available.

This works in plain R scripts via the vscode-R extension and would be very helpful to have in Quarto too. (Indeed it is one of the VS Code features which makes it easier to navigate especially more complicated code bases in VS Code than in RStudio.)

**Comment by jjallaire** [comment]
Thanks for the feedback! This actually wasn't too difficult to implement: https://github.com/quarto-dev/quarto/commit/3d4ee144bb27aa1094dd810cdaba0f20e09c7bd1

This will be available in the next release of the extension (likely early next week)

**Comment by petrbouchal** [comment]
Thank you for the quick fix - now works as expected, excellent.
