### ISSUE TITLE
VS Code - Project is not rendered when the terminal is in the editor area.

### ISSUE THREAD

**Issue by Adam-Antios** [quarto-dev/quarto#61]
I am using VS Code Insiders 1.75.0. I have experienced the issue I will describe in both Windows 10 (with WSL as a backend) and Ubuntu 22.10.

On VS Code if the following option is enabled:

```
"terminal.integrated.defaultLocation": "editor"
```

then rendering a quarto project does not work the first time.

More specifically, when I press the render button the first time I open a project, then a terminal is created in the editor area, but it is "stuck" in a state of  loading without presenting any output, while the project itself is not rendered. Once I repeat this process, the terminal reloads, outputs the appropriate messages and the project is rendered as it should.

**Comment by jjallaire** [comment]
I was able to reproduce this -- seems like some sort of state/timing issue in the VS Code editor terminal implementation. I think I was able to work around this by just inserting a console.log right before I show the terminal: https://github.com/quarto-dev/quarto/commit/7c6623a21236b4cd7aee64042a3e98a69efa2753
