### ISSUE TITLE
re-use markdown textmate highlighting rules?

### ISSUE THREAD

**Issue by tecunningham** [quarto-dev/quarto#63]
I have a lot of TextMate rules that make Markdown look good in VS-code, but they're not being applied to markdown inside Quarto documents.

The reason is that In quarto the scopes are called things like `heading.1.quarto`, while in markdown the same thing is called `heading.1.markdown`.

Is there any way of having a set of textmate rules which applies to both, or will I have to maintain two separate ones?

**Comment by jjallaire** [comment]
We specifically don't inherit the default markdown rules b/c there are too many subtle differences to make work properly (so in short yes you would need to maintain two separate ones)
