### ISSUE TITLE
VS Code / Jupyter is not available in this Python installation

### ISSUE THREAD

**Issue by fenke** [quarto-dev/quarto#65]
Rendering a book project with python code cells in VS Code yields the the following in the quarto terminal:

    (jupyter-base) fenke@denkdoosje:~/repos/notebooks/wodan-ref> quarto render --to pdf
    [1/4] index.qmd
    [2/4] chapters/intro.qmd

    Starting python3 kernel...Traceback (most recent call last):
      File "/home/fenke/opt/quarto-1.2.313/share/jupyter/jupyter.py", line 21, in <module>
        from notebook import notebook_execute, RestartKernel
      File "/home/fenke/opt/quarto-1.2.313/share/jupyter/notebook.py", line 16, in <module>
        import nbformat
    ModuleNotFoundError: No module named 'nbformat'
    Python 3 installation:
      Version: 3.10.8
      Path: /usr/bin/python3.10
      Jupyter: (None)

    Jupyter is not available in this Python installation.
    Install with python3 -m pip install jupyter

The conda environment is activated from  ~/.bashrc, rendering from a system terminal works fine, rendering from a regular terminal in VS Code works fine too. But command keeps using the system python and the result is this error.

**Comment by dr563105** [comment]
I'm also getting the same error. I'm in M1 Mac.

I'm just starting Quarto. I copy the contents given [here](https://quarto.org/docs/get-started/hello/neovim.html#render-and-preview) to a test file. 

When I click "render" on the top right, it opens a new shell automatically, executes `quarto preview <filepath>/test.qmd --no-browser --no-watch-inputs` and gives out the above error. 

I have `conda` installed and in a new shell it is always `base` env where neither Jupyter nor any of the libraries are not installed. It is in this `base` env, Quarto runs the preview command. Even launching vscode inside the terminal after activating the necessary conda env, doesn't work.

Also after showing the above error, "rendering test.qmd" is endlessly looping.

Only workaround I found is to manually select python interpreter to the desired env and then hit "render".

**Comment by jjallaire** [comment]
Yes, it is the case that you need to set the default python interpreter explicitly (this enables quarto render to be in sync w/ the terminal and jupyter interactive console). Currently we call the Python extension's API to get the appropriate exec command for Python (it in turn has hundreds of lines of code dedicated to sorting out which version of python you want to use!). This should in turn respect the `python.defaultInterpreterPath` setting.
