### ISSUE TITLE
Add Quarto Treesitter grammar

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto#66]
[Treesitter](https://tree-sitter.github.io/tree-sitter/) is a library that can build a concrete syntax tree for a source file and efficiently update the syntax tree as the source file is edited. It is used in Neovim and as of lately also by Emacs to provide fast and more precise syntax highlighting and handy code navigation and editing features.

So far I have been using the basic treesitter [grammar for markdown](https://github.com/MDeiml/tree-sitter-markdown) in `quarto-nvim` (mostly to get the code chunks), but I have now learned that we don't have to write an entirely new grammar for Quarto, it can also be configured to extend the existing markdown grammar (https://github.com/nvim-treesitter/nvim-treesitter/pull/4212), which will benefite users across Neovim and Emacs (not VS Code so far, I think they are still going with their own internal parser, though it would be cool if they adopted it. Treesitter feels like the parser equivalent of the LSP).

I am currently a bit short on time, but if I get around to trying this, should we put this under the `quarto-dev` organization as well, @jjallaire?

**Comment by jjallaire** [comment]
Actually, tree sitter is pretty widely used by more advanced VS Code extensions. LSPs can now register a semantic token provider (as an alternative to the pattern based TextMate grammars) and many people are using tree sitter to implement the token provider). We actually currently use tree sitter for our YAML completion/diagnostics.

We are definitely interested in pursuing this! Note thought that Pandoc markdown does have quite a bit more going on than CommonMark so it will take some substantial work to create a proper tree sitter grammar. Definitely on our radar and would more than welcome your ideas and participation in the effort.

**Comment by jjallaire** [comment]
I'm going to close this issue as we are definitely aware of this as a possible way to improve / develop our LSP. We will be revisiting the LSP later this year and will definitely stay in sync with you so you can incorporate into neovim!
