### ISSUE TITLE
Update to mermaid-js 9.3

### ISSUE THREAD

**Issue by jmcastagnetto** [quarto-dev/quarto#67]
The new version (https://github.com/mermaid-js/mermaid/releases/tag/v9.3.0) has a reduced size, and several updates to the available language, including support to, for example, titles in a YAML block. The latter breaks the quarto preview in (at least) VSCode as seen below.

![Error when previewing mermaid diagram (VSCODE)](https://user-images.githubusercontent.com/364668/215347546-16244e11-c441-47cf-a3ba-e3d3dcbfec1b.png)

The diagram

```mermaid
---
title: Function execution process
---

stateDiagram-v2
    [*] --> Cool
    Cool --> Cool2
    Cool2 --> API1
    Cool2 --> API2
    API2 --> Cool2
    Cool2 --> API3
    Cool2 --> [*]
```

Seems to work OK with github rendering an also when using the CLI version of mermaid:

```sh
$ mmdc -o overall-process.png -i overall-process.mmd 
Generating single mermaid chart
```

![overall-process.png](https://user-images.githubusercontent.com/364668/215347805-1aa092e0-7cb8-4342-8ff0-f8801f4b99fd.png)

**Comment by jjallaire** [comment]
Thanks for reporting this! Addressed here: https://github.com/quarto-dev/quarto/commit/9a794e89f1f74d4f830148880d19ffabadfbf95c
