### ISSUE TITLE
error : '--no-save', '--no-restore'" terminated with exit code: 1.

### ISSUE THREAD

**Issue by shmuhammad2004** [quarto-dev/quarto#7]
Hi, 

Thank you for the good work.

I cannot run quarto in Vscode, I am having this error:

`"/Users/username/mambaforge/envs/datascience/bin/Radian '--no-save', '--no-restore'" terminated with exit code: 1.
`

**Comment by andycraig** [comment]
This may be due to your vscode-R settings, rather than a problem with Quarto. What happens when you run this in your terminal?

```sh
/Users/username/mambaforge/envs/datascience/bin/Radian --no-save --no-restore
```
