### ISSUE TITLE
Cells run in wrong folder?

### ISSUE THREAD

**Issue by kellertuer** [quarto-dev/quarto#73]
I am getting started with more Quarto in Julia recently.
For a new package I am trying to write my examples in Quarto.
The examples are in a `examples/` subdirectory with their own `Package.toml` for reproducibility.
This currently also includes the preliminary version of the new package, but also other dependent packages that I need.

Hence my first code cell looks like

````
```{julia}
#| echo: false
using Pkg;
Pkg.activate("."); # use the example environment,
```
````

If I now call `quarto render MyExample.qmd` in the `examples/` folder – this all works fine, it activates the `examples/` environment, loads the necessary packages and renders fine.

If I in comparison click on “Run cell” in the VS Code extension, it runs the cell, but in the packages main folder (and not in the examples subfolder). So – this activates the _wrong_ environment and all subsequent cells fail due to not being dependencies of my package but just packages I need for the example.

So – is there a way to specify – maybe in the `quarto.yml` the folder Julia code should be run in? That would be great.

**Comment by jjallaire** [comment]
Playing around with the Julia extension, it looks like all code execution occurs in the _current working directory_ rather the file from which the code is executed from. We actually call the Julia extension to execute the code so we are inheriting this behavior. So I'd say that there are two ways forward:

(1) Arrange to change the working directory in your Julia session before executing.

(2) If there is some way that the Julia extension can be invoked (or enhanced) to execute within the file's directory (or even to take an argument that allows changing the working dir) let us know by re-opening this issue and we'll make that connection.

**Comment by kellertuer** [comment]
Concerning (1) I tried a lot, but even changing folder on Terminal does not help, it seems for the extension always the Packages main folder is the working directory, I could not find out how to switch that.

(2) I have completely no clue about the Julia extension of quarto, I am happy that I got all of that working on my computer, but for now the “Run Code” button is basically useless for me if it behaves differently from what `quart render file.qmd` does with the same code cells on terminal.
This inconsistency would be nice if we could get rid of?

**Comment by jjallaire** [comment]
I would also like to get rid of this inconsistency! However, we don't actually run the Julia code (we hand that over to the Julia extension) so we don't have control over what the working directory is. Looking at the code, there isn't currently any logic to change the working directory so I think this needs to be done manually in the terminal (I was able to get this to work in my environment by using the Julia `cd()` function)

**Comment by kellertuer** [comment]
ah the `cd()` function might actually help. Maybe I'll check with the Julia VSCode Extension guys as well, whether they have an idea.

**Comment by jjallaire** [comment]
You can let them know that we call the `executeInREPL()` function they export from their extension. This does have a bunch of options on it already, if they could add a `cd` option then we could specify this to let them know they should ensure that this is the working directory before executing.

**Comment by jjallaire** [comment]
Re-opening in hopes of being able to implement a fix

**Comment by kellertuer** [comment]
Thanks I am currently writing the issue over there :)

**Comment by eitsupi** [comment]
The same problem exists for Python and R.
And, it seems that only Python uses the file path as the starting point, not the project root.

This means that if Quarto is set to `execute-dir: project` to match Julia or R, sequential Python execution on VS Code will fail.

**Comment by jjallaire** [comment]
Remember that when we execute R or Python code we are doing so using the R and Python extensions, not an internal Quarto project aware mechanism. Our APIs to those extensions are very narrow ("run this code") and don't let us control working directories, etc.. My guess is that these extensions use the current working directory, but its worth looking under the hood to see for sure. In any case customization of this behavior is beyond the ability of the Quarto extension.

**Comment by eitsupi** [comment]
Thanks for your response.

There is a setting called `jupyter.notebookFileRoot` in the Jupyter extension, which seems to allow changing the working directory to the project root.
https://github.com/microsoft/vscode-jupyter/issues/3605#issuecomment-533861244

I think it is worth mentioning in the Quarto document.

**Comment by kellertuer** [comment]
Hm, the original issue is that if I hit `Shift+Enter` in the VS Code Quarto extension, then this is run in the wrong folder. Where would I add the `cd` there (during/while hitting Shift+Enter?!)

**Comment by jjallaire** [comment]
You need to do the `cd()` prior to executing `Command+Shift+Enter` (i.e. set up your terminal as you want it, then execute code)

**Comment by jjallaire** [comment]
You do `cd()` within the R session. I agree with you about the config file, but we don't have any control over the execution environments provided by other extensions.

**Comment by kellertuer** [comment]
I really have to take a closer look here, since I have _never_ used any `R` nor is it installed on my machine (at least I thought so), I was under the impression that my Markdown-Quarto-with-Julia notebook would evaluate using Jupyter/Python?

Well, as I said – I am basically now totally confused.

**Comment by eitsupi** [comment]
@kellertuer Julia and R extensions always start from the project root, but the Python extension is configurable. I think that's it.

**Comment by kellertuer** [comment]
Ah, I was just wondering, because my initial request was just about Julia (and it might use Jupyter and Python in between) – but it never uses `R`.

Well, I still have to find time to check how and when the `cd` should be used then.
