### ISSUE TITLE
Running cell in qmd file ignores decorator

### ISSUE THREAD

**Issue by JanPalasek** [quarto-dev/quarto#75]
If I run these cells separately in qmd file in VSCode (Run Selected cell), then the second one will have the decorator ignored.

```{{python}}
def my_decorator(fn):
  return my_decorator
```

```{{python}}
@my_decorator
def f(a, b):
  return a + b
```

![image](https://user-images.githubusercontent.com/26582151/217350534-0da954ae-b3f8-40e1-8050-cc53e4266922.png)

Quarto extension version: v1.61.0.

**Comment by jjallaire** [comment]
We are executing the Python code by calling the Python extension (specifically by executing the `jupyter.execSelectionInteractive` command). It looks like something within this command is stripping the decorator (I can reproduce if I run from a standard .py file by selected the code and executing the "Run Selection/Line in Interactive Window" command).

**Comment by jjallaire** [comment]
I'd suggest filing an issue on the VS Code Python extension repo (https://github.com/microsoft/vscode-python/issues) to ask about respecting decorators when using the "Run Selection/Line in Interactive Window" command.

**Comment by JanPalasek** [comment]
Done: https://github.com/microsoft/vscode-python/issues/20664 .

**Comment by jjallaire** [comment]
Thanks!
