### ISSUE TITLE
Visual editor: can't include code block after a paragraph with footnote

### ISSUE THREAD

**Issue by hadley** [quarto-dev/quarto#82]
Open a new quarto file in source mode and add the following

```
First sentence.
Second sentence.[^1]
Third sentence.

[^1]: A footnote
```

Switch to visual mode and add a code block by typing ```` ``` ```` and type `abc`.

Switch back to source mode.

Switch back to visual mode.

The code chunk has "disappeared" because it has been inlined into the footnote.

**Comment by jjallaire** [comment]
I'm not able to repro this at least in the current development version of the editor (which in theory should be getting into the daily build of RStudio).

What does the contents of the source editor look like after you switch back into it from the first trip into visual mode?

**Comment by hadley** [comment]
I still see it in the daily (Version 2023.03.0-daily+313)

Source contents look like:

```
First sentence.
Second sentence.[^1]
Third sentence.

[^1]: A footnote

    abc
```

**Comment by hadley** [comment]
A possibly simpler reprex is to start with this in source mode:

```R
First sentence.
Second sentence.[^1]
Third sentence.

    abc

[^1]: A footnote
```

and then switch to visual mode.

**Comment by jjallaire** [comment]
This looks like a markdown parsing ambiguity (it thinks the code block is just part of a multi-block footnote). You could prevent this by adding the  the `default` language to the code block (so Pandoc no longer indents it 4 spaces):

````markdown
First sentence.
Second sentence.[^1]
Third sentence.

[^1]: A footnote

``` default
abc
```
````

We could do this automatically for code blocks with no language but I'm not sure if people would like the injection of `default`. We could also add a fake sentinel language value and post process to remove it?

**Comment by jjallaire** [comment]
The lack of back ticks on code blocks w/o attributes has always bothered me, this provides some additional motivation to clean this up. Done here: https://github.com/quarto-dev/quarto/commit/ba960c2119dfae5faac7bb8b6e074f34f8d48d4b

**Comment by hadley** [comment]
That’s always bothered me too 😀
