### ISSUE TITLE
Run above will fail when you use magics, because it now "Run Jupyter cells in one shot"

### ISSUE THREAD

**Issue by edalfon** [quarto-dev/quarto#83]
Hi guys,

I just noticed https://github.com/quarto-dev/quarto/commit/09d495db64df5b27d9b8d80ecafd26997ac163e4, in some cases, breaks the `Run Above` part of my quarto workflow.

Basically, clicking `Run Above` will fail whenever there are chunks that use magics interweaved up there. That was working fine until `1.62.0`, so I guess the culprit is https://github.com/quarto-dev/quarto/commit/09d495db64df5b27d9b8d80ecafd26997ac163e4. Now, all chunks get concatenated into a single cell and therefore, if there are magics in a code chunk, you could end up with some magics syntax in the middle of the single cell, leading to a syntax error.

Here's a minimal reprex where I noticed the issue (using sqlalchemy to write sql chunks). 

````
---
title: "Run Above"
---

```{python}
import duckdb
import sqlalchemy 
%load_ext sql

%sql duckdb:///:memory:
```

```{python}
%%sql

SELECT 1;
```

```{python}
print('Hello World')
```
````

If you click run above in the chunk printing hello world, it fails with this syntax error. (it works up until version 1.62.0, and also rendering the whole document works fine. It's just the run above button).
```
Cell In[1], line 10
    SELECT 1;
           ^
SyntaxError: invalid syntax
```

Here's another example where you can get unexpected results by joining all chunks into a single cell. In this case, clicking `Run Above` in the hello world chunk will not lead to an error, because `%%timeit` magic was used in the first chunk. So it is still syntactically valid when all chunks are combined into a single cell. Yet, you end up timing both time.sleep(1) and time.sleep(5), when you only wanted to time the first one.

`````
---
title: "Run Above"
---

```{python}
%%timeit
import time
# wanted to time this
time.sleep(1)
```

```{python}
import time
# but didn't want to time this
time.sleep(5)
```

```{python}
print("Hello World")
```
`````

Is there any chance you can make sure the chunks run in the correct order, which is the aim of https://github.com/quarto-dev/quarto/commit/09d495db64df5b27d9b8d80ecafd26997ac163e4, but without lumping all chunks into a single cell? Thanks!

**Comment by jjallaire** [comment]
Now I remember why we run ended up running cells separately! (the magics).

The out of order execution seems pretty terrible to me (and I'm not sure how to mitigate it). I will play around to see if there is some other way.

One possible resolution would be to explicitly look for magics in cells and always run those cells individually?

**Comment by jjallaire** [comment]
I just reverted this change and published a new version of the extension (v1.65.0) with this change. Thanks for reporting!

**Comment by edalfon** [comment]
thx jj for such a quick reaction and fix.

> The out of order execution seems pretty terrible to me (and I'm not sure how to mitigate it). I will play around to see if there is some other way.

Totally agree that out of order execution would be pretty terrible. I haven't experience it, though. I have just tried to induce that behavior without luck, so I was wondering when can that happen. (I guess due to `async`, that's a possibility, but no idea if someplace else the order is being enforced).

**Comment by jjallaire** [comment]
I wonder if the issue is that there are particular cells that appear to complete but have some sort of async behavior (so out of order isn't a general problem but rather something that can happen for particular incantations)
