### ISSUE TITLE
Quarto commands not found in VS Code extension

### ISSUE THREAD

**Issue by artkuo** [quarto-dev/quarto#85]
In 1.60.0 - 1.66.0 while running VS Code 1.75.1 (MacOS 13.1), the quarto commands such as `quarto.clearCache` are not found, the Render buttons don't work, and `Run cell` button doesn't show up. Syntax highlighting does still work in the editor window, and Quarto 1.2.335 is displayed on the bottom status bar. The Quarto commands do auto-complete in the Command Palette, they just don't run, returning errors such as "command 'quarto.clearCache' not found". 

All of these things still work on 1.59.0, but none after that.

I suspect this is not common because I didn't see other issues filed. I tried re-installing VS Code (same version) and Quarto 1.2.335 but no effect.

**Comment by jjallaire** [comment]
There is likely an exception occurring during startup. Try executing the "Developer: Toggle Developer Tools" command and then reload VS Code with the "Developer: Reload Window" command. You will likely see a JavaScript exception reported in the "Console" tab of the developer tools pane on the right. Take a screenshot of that and hopefully we'll have a better idea (try to do this w/ v1.66.0 so I can map the line numbers).

**Comment by artkuo** [comment]
The issue was that my user settings.json was invalid (due to a different extension). This causes Quarto extension v1.60+ to abort, whereas 1.59 still worked. Obviously bad settings.json is problematic. With a fixed json file, v1.60+ seem to work fine. Nevertheless, I'll attach screen shots below since there's a difference in robustness.
 
First, with the bad json in v1.59, note `ERR: Unable to write into user settings  workbench.desktop.main.js:616`. :
<img width="528" alt="Screenshot 2023-02-19 at 5 07 32 PM" src="https://user-images.githubusercontent.com/2893800/219983990-5b87fd70-d63e-49ed-ae88-9432591ce5bb.png">


With bad json in v1.67, the error is now `Activating extension 'quarto.quarto'  workbench.desktop.main.js:2020`. :
<img width="529" alt="Screenshot 2023-02-19 at 5 08 51 PM" src="https://user-images.githubusercontent.com/2893800/219984284-a048038f-388c-4736-8818-a8485ace7ba9.png">


With a fixed json, the problem disappears. It seems that v1.59 was more robust to corrupt json, but otherwise there are no issues with the newer versions. Thanks for your tips.

**Comment by jjallaire** [comment]
Brilliant! Thanks so much for the additional diagnostics. I have a fix applied here: https://github.com/quarto-dev/quarto/commit/79e52829e25e712037f66d6d1dee74849579e73f
