### ISSUE TITLE
Do not modify Code/User/settings.json on startup

### ISSUE THREAD

**Issue by heavywatal** [quarto-dev/quarto#86]
The VSCode plugin adds `"quarto.mathjax.theme": "dark"` at the end of `Code/User/settings.json` every time a directory tree with some `.qmd` files is opened.

**Comment by jjallaire** [comment]
The problem this is intended to address is showing the correct light vs. dark SVG preview for math in the source editor. Currently VSCode doesn't provide a way for an LSP to detect whether it is in light or dark mode, although we can definitely work around this though by accessing `workbench.colorTheme` and then inspecting all of the installed extensions as described here: https://stackoverflow.com/questions/58769192/programmatically-detect-light-vs-dark-colour-theme

Thanks for reporting this, will try to resolve soon!

**Comment by jjallaire** [comment]
Okay, I've made this change here: https://github.com/quarto-dev/quarto/commit/1f05b10be0323a8a794a51df65cec199566a0965

Should be available in a new release within the next few days.
