### ISSUE TITLE
Specified QUARTO_PYTHON 'python3' does not exist.

### ISSUE THREAD

**Issue by m-pauper** [quarto-dev/quarto#87]
Hello,

I have install quarto using the .deb package.

Quarto check seems ok:

```
[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/mpauper/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

I then installed Quarto in VS codium, using the extensions tab.

I then tried to render the file given at the beginning of this [tutorial](https://quarto.org/docs/get-started/hello/vscode.html).

I then see the following in the VS codium terminal:

```
❯ quarto preview /home/mpauper/dt/scratch/workspace/Solve-RD-proteomics/test/hello.qmd --no-browser --no-watch-inputs
WARNING: Specified QUARTO_PYTHON 'python3' does not exist.
WARNING: Specified QUARTO_PYTHON 'python3' does not exist.

Starting python3 kernel...Done

Executing 'hello.ipynb'

pandoc 
  to: html
  output-file: hello.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Basics
  jupyter: python3
  
WARNING: Unable to resolve crossref @fig-polar
Output created: hello.html

Watching files for changes
Browse at http://localhost:3856/
```

and the preview window shows this:
![image](https://user-images.githubusercontent.com/92805868/219346950-2b7bc4a8-4760-410c-8de7-6f736b752fd2.png)

If I try the same preview command directly in an external terminal I do not have the missing python3 warning:

```
❯ quarto preview test/hello.qmd --no-browser --no-watch-inputs 

Starting python3 kernel...Done

Executing 'hello.ipynb'

pandoc 
  to: html
  output-file: hello.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Basics
  jupyter: python3
  
WARNING: Unable to resolve crossref @fig-polar
Output created: hello.html

Watching files for changes
Browse at http://localhost:6126/
```

However the preview at localhost is the same, but that is probably related to the `@fig-polar` error that I have not looked into yet.

How can I make sure quarto extension can find my python3 just like in my terminal?

Here is the `quarto check` from within Codium's internal terminal:

```
[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

WARNING: Specified QUARTO_PYTHON 'python3' does not exist.
[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

(|) Checking Jupyter engine render....WARNING: Specified QUARTO_PYTHON 'python3' does not exist.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/mpauper/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
> WARNING: Specified QUARTO_PYTHON 'python3' does not exist.

This  warning means that somewhere the environment variable `QUARTO_PYTHON ` is set to the value `python3`. Do you know if you have set this environment variable somewhere for your project, session or else ? You could check in VSCODE terminal if this variable is indeed set to the value indicated.  If you did not set it, we need to find where that comes from. 

For context in VSCODE, `QUARTO_PYTHON` is a way to use a virtualenv I believe;

**Comment by m-pauper** [comment]
Thanks for the swift reply!

Indeed, from codium's internal terminal `echo $QUARTO_PYTHON` returns `python3`. 

I can see from my Codium user settings that I have `"python.defaultInterpreterPath": "python3",` although I don't remember why or when I set that. Is that causing the problem? Should I try simply removing that line from the settings?

**Comment by cderv** [comment]
I don't know if this gets assigned to `QUARTO_PYTHON` env var. You could try removing the config and see if it changes; 
Otherwise, there could be another configuration that sets the env var.

**Comment by m-pauper** [comment]
Removing that line from `settings.json` has fixed the issue.

Thank you for the quick help!

**Comment by jjallaire** [comment]
Interesting! We actually do set `QUARTO_PYTHON` based on `python.defaultInterpreterPath`. It seems like we should be checking for existence and/or resolving that to a full path. Will re-open to track that change.

**Comment by jjallaire** [comment]
We now resolve the path here: https://github.com/quarto-dev/quarto/commit/d3b299be53f0899a9d9de52ac5a7b6dd003d6452

Also do the same in quarto-cli: https://github.com/quarto-dev/quarto-cli/commit/82643d1afbdf450e50ac691ce4fd4bf1ee3f255a
