### ISSUE TITLE
Citation preview don't work for larger bib file

### ISSUE THREAD

**Issue by andreatitolo** [quarto-dev/quarto#90]
I have a .bib file around 2MB in size. When I use this in VSCode (both editor and visual mode), the preview for selecting citations does not appear. 

If I split the file in 2-3 different bib files, the citation picker shows up perfectly for each one of them, but this is not ideal of course. 
The same .bib file works perfectly in Rstudio.

**Comment by jjallaire** [comment]
Hi there, is there any way you could make your bibliography file available to us so that we can reproduce this locally? Thanks!

**Comment by andreatitolo** [comment]
Hi! Sure, here it is, the link should work: https://drop.infini.fr/r/xAMzZzm6g8#Fl9/ON7NHZ71xzpJGmNaqHODKI0V+z6UklD+6Zr+byY=

Thank you in advance :)

**Comment by jjallaire** [comment]
Thanks! Will try to reproduce this locally and hopefully report back with a fix.

**Comment by andreatitolo** [comment]
> Thanks! Will try to reproduce this locally and hopefully report back with a fix.

Thank you for your help :)

**Comment by jjallaire** [comment]
Brilliant! That did the trick (we needed a larger default buffer size for executing pandoc to read the bibliography: https://github.com/quarto-dev/quarto/commit/00dba0e826b4f7266c29c050f736b7c7ab3264cf)

New release with this fix should be available in the next few days.
