### ISSUE TITLE
VS Code extension: Switching to Visual Mode replaces footnote identifiers chosen by the user with numbers

### ISSUE THREAD

**Issue by magical-heyrovsky** [quarto-dev/quarto#94]
### Bug description

When switching from Source Mode to Visual Mode, Quarto replaces all the footnote identifiers chosen by the user and replaces them with numbers.

The problem is best explained with this video:

[Screencast.webm](https://user-images.githubusercontent.com/101060148/220174374-2613bc7b-c2c7-4668-896c-67638041d81a.webm)

File in the video: [chapter02.md](https://github.com/quarto-dev/quarto-cli/files/10786880/chapter02.md) (GitHub does not allow `qmd` files so I had to change it to `md`)

Quarto CLI version: 1.2.335
VS Code version: 1.75.1
VS Code extension version: 1.68.0
OS: Ubuntu 22.10

**Comment by jjallaire** [comment]
We use Pandoc to parse the markdown, and footnote identifiers are not carried along into the markdown document AST. So this is unfortunately a known limitation of the visual editor. If Pandoc does add footnote identifiers to the AST we will definitely support them in the editor.
