### ISSUE TITLE
Use formatting for Julia with qmd files with VS Code

### ISSUE THREAD

**Issue by jlperla** [quarto-dev/quarto#95]
It would be great to be able to use the code formatting commands with the Julia (and all) languages.  I imagine using this with `> Format Selection` rather than the whole file, but it would be great to have both.

In Julia the code formatter is https://github.com/domluna/JuliaFormatter.jl  where it is standard to have a `.JuliaFormatter.toml` file in your directly giving settings and is used if found when recursively walking up the tree from the file location.  A good test case is just to have that file as
```toml
style = "sciml"
```

In the longrun you may want to control that all of that in your own extension, but in the shortrun it might be easy to provide this feature by patching the Julia VS Code extension to suport quarto files with formatting (which anyone using julia would have installed). 
 See https://github.com/julia-vscode/julia-vscode/issues/3166  for a posting of the issue there.

**Comment by jjallaire** [comment]
As of a recent release of the extension we do indeed support formatting. You can currently format selections or do a "Format Document" while your cursor is within a Julia cell and it should work. Note this will only work if the Julia extension registers a standard code formatter w/ VS Code (as we delegate to it). I should also say that while I have tested this with R and Python I haven't yet with Julia. Let me know what you find out.

**Comment by jjallaire** [comment]
I just tested with embedded Julia cells in `.qmd` and both Format Document and Format Range both seem to work!
