### ISSUE TITLE
Quarto file gets newline after every character on save

### ISSUE THREAD

**Issue by tecunningham** [quarto-dev/quarto#96]
A weird intermittent issue: when I'm editing a `qmd` file sometimes newlines get inserted after every character for some subset of text, see image below. I've used vscode for a long time and never seen this before, it seems to be specific to `qmd` files. I'm not sure if it happens just when I save a file. 

It's usually near the bottom of the file. Maybe it's some auto-formatting process? I've disabled "editor.formatOnSave" and will see if it helps. 

<img width="571" alt="image" src="https://user-images.githubusercontent.com/14047958/221236197-723605f6-39b4-493f-8b24-fa6bfba98680.png">

**Comment by jjallaire** [comment]
Interesting! If you have format on save configured then we do now run the formatter of any language where your cursor is currently located (e.g. if your cursor is in a Python, R, or Julia code cell and you have format on save configured we will run the respective language formatter against just the code cells for that language).

It's possible that this is having some sort of unexpected side effect though. Could you confirm whether this occurs for you when you are inside a code cell? (the Format Document command should also trigger the behavior if you no longer have `formatOnSave` configured). If that does trigger the behavior, could you post the file where you see it as well as which formatter you are using?

**Comment by jjallaire** [comment]
I made a change to ensure that other formatters never run over `.qmd` files (which could have been the case if your cursor wasn't in an R, Python, or Julia block) and also made sure that we don't run formatting for `.md` files: https://github.com/quarto-dev/quarto/commit/b0bf107e4c8d1cee981ed42a5a2e74c134c59407. This is available in the v1.70.0 release.

**Comment by tecunningham** [comment]
Apologies for not responding earlier, thanks for the detailed response. 

I haven't had a problem since I disabled format-on-save. I'll re-enable it when I update to v1.70.0, and post back here if there's any problem.

**Comment by jjallaire** [comment]
Okay, great. Thanks! I will also re-open this just as a reminder to check back in on whether the problem is resolved.
