### ISSUE TITLE
vscode: Supply mathjax macros for math-preview and display-mode editing?

### ISSUE THREAD

**Issue by tecunningham** [quarto-dev/quarto#97]
I have some mathjax macros that I use a lot. 

I would like to define those macros so quarto extension in vscode can use them when rendering maths in (1) "visual mode" editing; or (2) the math preview pane.

(I know how to add mathjax macros to the YAML of a Quarto document so they'll display in the generated HTML, but that YAML doesn't seem to inform the preview-pane or visual-mode rendering of maths).

**Comment by jjallaire** [comment]
I believe that if you define the macros within a raw tex block within the document they will be picked up by both visual mode and the math preview pane.

That said, I believe that we pick up the macro definitions using a regex over the whole document so if you can provide a minimal example of your YAML definitions that don't work I can see if we can pick those up as well.

**Comment by tecunningham** [comment]
Oh thanks so much, problem solved. Apologies if this was already in documentation and I missed it. 

The following works for me with both preview-pane and visual-mode:

````{quarto}

```{latex}
\newcommand{\ut}[2]{\underbrace{#1}_{\text{#2}}}
```

$$\ut{x^2}{caption}$$
````

**Comment by jjallaire** [comment]
Okay, great! Glad to hear this works as expected. This isn't in the docs so easy to miss (will remedy that).
