### ISSUE TITLE
Font Color for Equations in Visual Editor Don't Swap Based on Dark/Light Theme Like Rest of Text

### ISSUE THREAD

**Issue by githubpsyche** [quarto-dev/quarto#98]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/33912594/221443823-6314ff23-1fcb-428d-afea-ef1e56e4c16d.png">

The font for the equations when using a dark theme should probably not be black but rather dynamically change in color in the same way the rest of the text's color does. This screenshot is more readable than what I see in practice.

(By the way, the visual editor is amazing! It has wildly changed how I work, especially since, for whatever reason, it plays a lot better with the Grammarly extension. I'm continually super impressed with what you guys are up to!)

**Comment by jjallaire** [comment]
We just changed the way we handle equation theme syncing and it looks like its not working the way it should be! Thanks for reporting, we should be able to resolve this soon.

**Comment by jjallaire** [comment]
Okay, this is now resolved here: https://github.com/quarto-dev/quarto/commit/c617dd628a501fb4f98aea8536fabf63c7a84664 (available in the updated v1.70.1 release)

**Comment by githubpsyche** [comment]
Wow thanks!
